// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/business/vod_upload.proto

package com.volcengine.service.vod.model.business;

public interface ApplyUploadInfoParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.ApplyUploadInfoParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  java.lang.String getSpaceName();
  /**
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  com.google.protobuf.ByteString
      getSpaceNameBytes();

  /**
   * <code>string FileType = 2;</code>
   * @return The fileType.
   */
  java.lang.String getFileType();
  /**
   * <code>string FileType = 2;</code>
   * @return The bytes for fileType.
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();

  /**
   * <code>string SessionKey = 3;</code>
   * @return The sessionKey.
   */
  java.lang.String getSessionKey();
  /**
   * <code>string SessionKey = 3;</code>
   * @return The bytes for sessionKey.
   */
  com.google.protobuf.ByteString
      getSessionKeyBytes();

  /**
   * <code>double FileSize = 4;</code>
   * @return The fileSize.
   */
  double getFileSize();

  /**
   * <code>string MediaType = 5;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <code>string MediaType = 5;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <code>string TosKeys = 6;</code>
   * @return The tosKeys.
   */
  java.lang.String getTosKeys();
  /**
   * <code>string TosKeys = 6;</code>
   * @return The bytes for tosKeys.
   */
  com.google.protobuf.ByteString
      getTosKeysBytes();

  /**
   * <code>string FileExtension = 7;</code>
   * @return The fileExtension.
   */
  java.lang.String getFileExtension();
  /**
   * <code>string FileExtension = 7;</code>
   * @return The bytes for fileExtension.
   */
  com.google.protobuf.ByteString
      getFileExtensionBytes();

  /**
   * <code>string FilePrefix = 8;</code>
   * @return The filePrefix.
   */
  java.lang.String getFilePrefix();
  /**
   * <code>string FilePrefix = 8;</code>
   * @return The bytes for filePrefix.
   */
  com.google.protobuf.ByteString
      getFilePrefixBytes();

  /**
   * <code>int32 FlushUploadMode = 9;</code>
   * @return The flushUploadMode.
   */
  int getFlushUploadMode();

  /**
   * <code>string Md5 = 10;</code>
   * @return The md5.
   */
  java.lang.String getMd5();
  /**
   * <code>string Md5 = 10;</code>
   * @return The bytes for md5.
   */
  com.google.protobuf.ByteString
      getMd5Bytes();

  /**
   * <code>int32 StorageClass = 11;</code>
   * @return The storageClass.
   */
  int getStorageClass();

  /**
   * <code>string UploadHostPrefer = 12;</code>
   * @return The uploadHostPrefer.
   */
  java.lang.String getUploadHostPrefer();
  /**
   * <code>string UploadHostPrefer = 12;</code>
   * @return The bytes for uploadHostPrefer.
   */
  com.google.protobuf.ByteString
      getUploadHostPreferBytes();

  /**
   * <code>string ClientNetWorkMode = 101;</code>
   * @return The clientNetWorkMode.
   */
  java.lang.String getClientNetWorkMode();
  /**
   * <code>string ClientNetWorkMode = 101;</code>
   * @return The bytes for clientNetWorkMode.
   */
  com.google.protobuf.ByteString
      getClientNetWorkModeBytes();

  /**
   * <code>string ClientIDCMode = 102;</code>
   * @return The clientIDCMode.
   */
  java.lang.String getClientIDCMode();
  /**
   * <code>string ClientIDCMode = 102;</code>
   * @return The bytes for clientIDCMode.
   */
  com.google.protobuf.ByteString
      getClientIDCModeBytes();
}
