// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_measure.proto

package com.volcengine.service.vod.model.business;

public interface DescribeVodSpaceDetectStatisDataItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.DescribeVodSpaceDetectStatisDataItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Time = 1;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string Time = 1;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>int64 Usage = 2;</code>
   * @return The usage.
   */
  long getUsage();
}
