// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/business/vod_cdn.proto

package com.volcengine.service.vod.model.business;

public interface HTTPSOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.HTTPS)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool Switch = 1;</code>
   * @return Whether the switch field is set.
   */
  boolean hasSwitch();
  /**
   * <code>optional bool Switch = 1;</code>
   * @return The switch.
   */
  boolean getSwitch();

  /**
   * <code>optional .Volcengine.Vod.Models.Business.CertInfo CertInfo = 2;</code>
   * @return Whether the certInfo field is set.
   */
  boolean hasCertInfo();
  /**
   * <code>optional .Volcengine.Vod.Models.Business.CertInfo CertInfo = 2;</code>
   * @return The certInfo.
   */
  com.volcengine.service.vod.model.business.CertInfo getCertInfo();
  /**
   * <code>optional .Volcengine.Vod.Models.Business.CertInfo CertInfo = 2;</code>
   */
  com.volcengine.service.vod.model.business.CertInfoOrBuilder getCertInfoOrBuilder();

  /**
   * <code>optional .Volcengine.Vod.Models.Business.ForcedRedirect ForcedRedirect = 3;</code>
   * @return Whether the forcedRedirect field is set.
   */
  boolean hasForcedRedirect();
  /**
   * <code>optional .Volcengine.Vod.Models.Business.ForcedRedirect ForcedRedirect = 3;</code>
   * @return The forcedRedirect.
   */
  com.volcengine.service.vod.model.business.ForcedRedirect getForcedRedirect();
  /**
   * <code>optional .Volcengine.Vod.Models.Business.ForcedRedirect ForcedRedirect = 3;</code>
   */
  com.volcengine.service.vod.model.business.ForcedRedirectOrBuilder getForcedRedirectOrBuilder();

  /**
   * <code>optional bool HTTP2 = 4;</code>
   * @return Whether the hTTP2 field is set.
   */
  boolean hasHTTP2();
  /**
   * <code>optional bool HTTP2 = 4;</code>
   * @return The hTTP2.
   */
  boolean getHTTP2();

  /**
   * <code>repeated string TlsVersion = 5;</code>
   * @return A list containing the tlsVersion.
   */
  java.util.List<java.lang.String>
      getTlsVersionList();
  /**
   * <code>repeated string TlsVersion = 5;</code>
   * @return The count of tlsVersion.
   */
  int getTlsVersionCount();
  /**
   * <code>repeated string TlsVersion = 5;</code>
   * @param index The index of the element to return.
   * @return The tlsVersion at the given index.
   */
  java.lang.String getTlsVersion(int index);
  /**
   * <code>repeated string TlsVersion = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tlsVersion at the given index.
   */
  com.google.protobuf.ByteString
      getTlsVersionBytes(int index);
}
