// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/business/vod_workflow.proto

package com.volcengine.service.vod.model.business;

public interface SnapshotParamsSampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.SnapshotParamsSample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Format = 1;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string Format = 1;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>repeated string StoreUris = 2;</code>
   * @return A list containing the storeUris.
   */
  java.util.List<java.lang.String>
      getStoreUrisList();
  /**
   * <code>repeated string StoreUris = 2;</code>
   * @return The count of storeUris.
   */
  int getStoreUrisCount();
  /**
   * <code>repeated string StoreUris = 2;</code>
   * @param index The index of the element to return.
   * @return The storeUris at the given index.
   */
  java.lang.String getStoreUris(int index);
  /**
   * <code>repeated string StoreUris = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the storeUris at the given index.
   */
  com.google.protobuf.ByteString
      getStoreUrisBytes(int index);

  /**
   * <code>int32 Width = 3;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 Height = 4;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>float Interval = 5;</code>
   * @return The interval.
   */
  float getInterval();

  /**
   * <code>int32 CaptureNum = 6;</code>
   * @return The captureNum.
   */
  int getCaptureNum();

  /**
   * <code>float Duration = 7;</code>
   * @return The duration.
   */
  float getDuration();

  /**
   * <code>string IndexUri = 8;</code>
   * @return The indexUri.
   */
  java.lang.String getIndexUri();
  /**
   * <code>string IndexUri = 8;</code>
   * @return The bytes for indexUri.
   */
  com.google.protobuf.ByteString
      getIndexUriBytes();

  /**
   * <pre>
   *采样截图自定义采样时间点
   * </pre>
   *
   * <code>repeated float Offsets = 9;</code>
   * @return A list containing the offsets.
   */
  java.util.List<java.lang.Float> getOffsetsList();
  /**
   * <pre>
   *采样截图自定义采样时间点
   * </pre>
   *
   * <code>repeated float Offsets = 9;</code>
   * @return The count of offsets.
   */
  int getOffsetsCount();
  /**
   * <pre>
   *采样截图自定义采样时间点
   * </pre>
   *
   * <code>repeated float Offsets = 9;</code>
   * @param index The index of the element to return.
   * @return The offsets at the given index.
   */
  float getOffsets(int index);
}
