// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_cdn.proto

package com.volcengine.service.vod.model.business;

public final class VodCdn {
  private VodCdn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainConfigInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainConfigInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainoInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainoInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainCertificateInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainCertificateInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCreateCdnTaskResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCreateCdnTaskResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodContentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodContentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnTaskResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnTaskResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodListCdnAccessLogResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodListCdnAccessLogResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnTopAccessUrlElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnTopAccessUrlElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodListCdnTopAccessUrlResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodListCdnTopAccessUrlResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodBandwidthData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodBandwidthData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainBandwidthDataResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainBandwidthDataResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsCommonResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsCommonResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodCdnIpInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodCdnIpInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDescribeIpInfoResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDescribeIpInfoResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodTrafficData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodTrafficData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainTrafficDataResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainTrafficDataResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainSourceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainSourceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodDomainOriginBucketInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodDomainOriginBucketInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodSubmitBlockTasksResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodSubmitBlockTasksResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_VodGetContentBlockTasksResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_VodGetContentBlockTasksResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Business_ContentTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Business_ContentTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032vod/business/vod_cdn.proto\022\036Volcengine" +
      ".Vod.Models.Business\032\035vod/business/vod_c" +
      "ommon.proto\"\350\001\n\023VodDomainConfigInfo\022\021\n\tS" +
      "paceName\030\001 \001(\t\022P\n\020PlayInstanceInfo\030\002 \001(\013" +
      "26.Volcengine.Vod.Models.Business.VodDom" +
      "ainInstanceInfos\022Q\n\021ImageInstanceInfo\030\003 " +
      "\001(\01326.Volcengine.Vod.Models.Business.Vod" +
      "DomainInstanceInfos\022\031\n\021DefaultPlayDomain" +
      "\030\004 \001(\t\"\265\001\n\026VodDomainInstanceInfos\022L\n\rByt" +
      "eInstances\030\001 \003(\01325.Volcengine.Vod.Models" +
      ".Business.VodDomainInstanceInfo\022M\n\016Other" +
      "Instances\030\002 \003(\01325.Volcengine.Vod.Models." +
      "Business.VodDomainInstanceInfo\"\232\001\n\025VodDo" +
      "mainInstanceInfo\022\022\n\nInstanceId\030\001 \001(\t\022?\n\007" +
      "Domains\030\002 \003(\0132..Volcengine.Vod.Models.Bu" +
      "siness.VodDomainoInfo\022\026\n\016CanSelfEditing\030" +
      "\003 \001(\010\022\024\n\014ConfigStatus\030\004 \001(\t\"\313\002\n\016VodDomai" +
      "noInfo\022\016\n\006Domain\030\001 \001(\t\022\r\n\005Cname\030\002 \001(\t\022\024\n" +
      "\014ConfigStatus\030\003 \001(\t\022\023\n\013CnameStatus\030\004 \001(\t" +
      "\022\016\n\006Status\030\005 \001(\t\022M\n\013Certificate\030\006 \001(\01328." +
      "Volcengine.Vod.Models.Business.VodDomain" +
      "CertificateInfo\022\022\n\nCreateTime\030\007 \001(\t\022\022\n\nU" +
      "pdateTime\030\010 \001(\t\022\016\n\006Region\030\t \001(\t\022D\n\007Sourc" +
      "es\030\n \003(\01323.Volcengine.Vod.Models.Busines" +
      "s.VodDomainSourceInfo\022\022\n\nLockStatus\030\013 \001(" +
      "\t\"\242\001\n\030VodDomainCertificateInfo\022\025\n\rCertif" +
      "icateId\030\001 \001(\t\022\027\n\017CertificateName\030\002 \001(\t\022\026" +
      "\n\016CertificatePub\030\003 \001(\t\022\026\n\016CertificatePri" +
      "\030\004 \001(\t\022\023\n\013HttpsStatus\030\005 \001(\t\022\021\n\tExpiredAt" +
      "\030\006 \001(\t\"(\n\026VodCreateCdnTaskResult\022\016\n\006Task" +
      "Id\030\001 \001(\t\"x\n\016VodContentInfo\022\016\n\006ItemId\030\001 \001" +
      "(\t\022\013\n\003Url\030\002 \001(\t\022\016\n\006Status\030\003 \001(\t\022\020\n\010TaskT" +
      "ype\030\004 \001(\t\022\027\n\017CreateTimestamp\030\005 \001(\005\022\016\n\006Ta" +
      "skId\030\006 \001(\t\"\217\001\n\020VodCdnTaskResult\022\022\n\nTotal" +
      "Count\030\001 \001(\005\022\017\n\007PageNum\030\002 \001(\005\022\020\n\010PageSize" +
      "\030\003 \001(\005\022D\n\014ContentInfos\030\004 \003(\0132..Volcengin" +
      "e.Vod.Models.Business.VodContentInfo\"\177\n\026" +
      "VodCdnAccessLogElement\022\023\n\013DownloadUrl\030\001 " +
      "\001(\t\022\020\n\010FileSize\030\002 \001(\003\022\020\n\010FileName\030\003 \001(\t\022" +
      "\026\n\016StartTimestamp\030\004 \001(\005\022\024\n\014EndTimestamp\030" +
      "\005 \001(\005\"n\n\023VodCdnAccessLogInfo\022\016\n\006Domain\030\001" +
      " \001(\t\022G\n\007LogList\030\002 \003(\01326.Volcengine.Vod.M" +
      "odels.Business.VodCdnAccessLogElement\"^\n" +
      "\031VodListCdnAccessLogResult\022A\n\004Logs\030\001 \003(\013" +
      "23.Volcengine.Vod.Models.Business.VodCdn" +
      "AccessLogInfo\"B\n\031VodCdnTopAccessUrlEleme" +
      "nt\022\013\n\003Url\030\001 \001(\t\022\n\n\002Pv\030\002 \001(\003\022\014\n\004Flux\030\003 \001(" +
      "\003\"k\n\034VodListCdnTopAccessUrlResult\022K\n\010Url" +
      "Infos\030\001 \003(\01329.Volcengine.Vod.Models.Busi" +
      "ness.VodCdnTopAccessUrlElement\"3\n\020VodBan" +
      "dwidthData\022\014\n\004Time\030\001 \001(\t\022\021\n\tBandwidth\030\002 " +
      "\001(\001\"\214\002\n\'VodDescribeVodDomainBandwidthDat" +
      "aResult\022\022\n\nDomainList\030\001 \003(\t\022\021\n\tStartTime" +
      "\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\023\n\013Aggregation\030\004" +
      " \001(\005\022\025\n\rBandwidthType\030\005 \001(\t\022\025\n\rPeakBandw" +
      "idth\030\006 \001(\001\022\031\n\021PeakBandwidthTime\030\007 \001(\t\022K\n" +
      "\021BandwidthDataList\030\010 \003(\01320.Volcengine.Vo" +
      "d.Models.Business.VodBandwidthData\"\200\001\n\024V" +
      "odCdnStatisticsData\022\014\n\004Name\030\001 \001(\t\022\016\n\006Met" +
      "ric\030\002 \001(\t\022\020\n\010DataType\030\003 \001(\t\0228\n\006Points\030\004 " +
      "\003(\0132(.Volcengine.Vod.Models.Business.Vod" +
      "Point\"\200\001\n\034VodCdnStatisticsCommonResult\022C" +
      "\n\005Datas\030\001 \003(\01324.Volcengine.Vod.Models.Bu" +
      "siness.VodCdnStatisticsData\022\033\n\023NoPermiss" +
      "ionDomains\030\002 \003(\t\"H\n\014VodCdnIpInfo\022\n\n\002Ip\030\001" +
      " \001(\t\022\r\n\005CdnIp\030\002 \001(\010\022\020\n\010Location\030\003 \001(\t\022\013\n" +
      "\003Isp\030\004 \001(\t\"V\n\027VodDescribeIpInfoResult\022;\n" +
      "\005Infos\030\001 \003(\0132,.Volcengine.Vod.Models.Bus" +
      "iness.VodCdnIpInfo\"/\n\016VodTrafficData\022\014\n\004" +
      "Time\030\001 \001(\t\022\017\n\007Traffic\030\002 \001(\001\"\350\001\n%VodDescr" +
      "ibeVodDomainTrafficDataResult\022\022\n\nDomainL" +
      "ist\030\001 \003(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTime\030" +
      "\003 \001(\t\022\023\n\013Aggregation\030\004 \001(\005\022\023\n\013TrafficTyp" +
      "e\030\005 \001(\t\022\024\n\014TotalTraffic\030\006 \001(\001\022G\n\017Traffic" +
      "DataList\030\007 \003(\0132..Volcengine.Vod.Models.B" +
      "usiness.VodTrafficData\"\254\002\n\023VodDomainSour" +
      "ceInfo\022U\n\021SourceStationType\030\001 \001(\0162:.Volc" +
      "engine.Vod.Models.Business.VodDomainSour" +
      "ceStationType\022c\n\030SourceStationAddressTyp" +
      "e\030\002 \001(\0162A.Volcengine.Vod.Models.Business" +
      ".VodDomainSourceStationAddressType\022\016\n\006Or" +
      "igin\030\003 \001(\t\022I\n\006Bucket\030\004 \001(\01329.Volcengine." +
      "Vod.Models.Business.VodDomainOriginBucke" +
      "tInfo\"_\n\031VodDomainOriginBucketInfo\022\022\n\nBu" +
      "cketName\030\001 \001(\t\022\030\n\020BucketSourceType\030\002 \001(\t" +
      "\022\024\n\014BucketRegion\030\003 \001(\t\"+\n\031VodSubmitBlock" +
      "TasksResult\022\016\n\006TaskID\030\001 \001(\t\"\214\001\n\035VodGetCo" +
      "ntentBlockTasksResult\022\r\n\005Total\030\001 \001(\003\022\017\n\007" +
      "PageNum\030\002 \001(\003\022\020\n\010PageSize\030\003 \001(\003\0229\n\004Data\030" +
      "\004 \003(\0132+.Volcengine.Vod.Models.Business.C" +
      "ontentTask\"`\n\013ContentTask\022\013\n\003Url\030\001 \001(\t\022\016" +
      "\n\006Status\030\002 \001(\t\022\020\n\010TaskType\030\003 \001(\t\022\022\n\nCrea" +
      "teTime\030\004 \001(\003\022\016\n\006TaskID\030\005 \001(\t*\222\001\n\032VodDoma" +
      "inSourceStationType\022\'\n#UndefinedVodDomai" +
      "nSourceStationType\020\000\022!\n\035VodVodDomainSour" +
      "ceStationType\020\001\022(\n$ThirdPartyVodDomainSo" +
      "urceStationType\020\002*\251\001\n!VodDomainSourceSta" +
      "tionAddressType\022.\n*UndefinedVodDomainSou" +
      "rceStationAddressType\020\000\022+\n\'DomainVodDoma" +
      "inSourceStationAddressType\020\001\022\'\n#IPVodDom" +
      "ainSourceStationAddressType\020\002B\312\001\n)com.vo" +
      "lcengine.service.vod.model.businessB\006Vod" +
      "CdnP\001ZAgithub.com/volcengine/volc-sdk-go" +
      "lang/service/vod/models/business\240\001\001\330\001\001\302\002" +
      "\000\312\002 Volc\\Service\\Vod\\Models\\Business\342\002#V" +
      "olc\\Service\\Vod\\Models\\GPBMetadatab\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.volcengine.service.vod.model.business.VodCommon.getDescriptor(),
        });
    internal_static_Volcengine_Vod_Models_Business_VodDomainConfigInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Volcengine_Vod_Models_Business_VodDomainConfigInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainConfigInfo_descriptor,
        new java.lang.String[] { "SpaceName", "PlayInstanceInfo", "ImageInstanceInfo", "DefaultPlayDomain", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfos_descriptor,
        new java.lang.String[] { "ByteInstances", "OtherInstances", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainInstanceInfo_descriptor,
        new java.lang.String[] { "InstanceId", "Domains", "CanSelfEditing", "ConfigStatus", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainoInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Volcengine_Vod_Models_Business_VodDomainoInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainoInfo_descriptor,
        new java.lang.String[] { "Domain", "Cname", "ConfigStatus", "CnameStatus", "Status", "Certificate", "CreateTime", "UpdateTime", "Region", "Sources", "LockStatus", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainCertificateInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Volcengine_Vod_Models_Business_VodDomainCertificateInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainCertificateInfo_descriptor,
        new java.lang.String[] { "CertificateId", "CertificateName", "CertificatePub", "CertificatePri", "HttpsStatus", "ExpiredAt", });
    internal_static_Volcengine_Vod_Models_Business_VodCreateCdnTaskResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Volcengine_Vod_Models_Business_VodCreateCdnTaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCreateCdnTaskResult_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_Volcengine_Vod_Models_Business_VodContentInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Volcengine_Vod_Models_Business_VodContentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodContentInfo_descriptor,
        new java.lang.String[] { "ItemId", "Url", "Status", "TaskType", "CreateTimestamp", "TaskId", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnTaskResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Volcengine_Vod_Models_Business_VodCdnTaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnTaskResult_descriptor,
        new java.lang.String[] { "TotalCount", "PageNum", "PageSize", "ContentInfos", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogElement_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogElement_descriptor,
        new java.lang.String[] { "DownloadUrl", "FileSize", "FileName", "StartTimestamp", "EndTimestamp", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnAccessLogInfo_descriptor,
        new java.lang.String[] { "Domain", "LogList", });
    internal_static_Volcengine_Vod_Models_Business_VodListCdnAccessLogResult_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Volcengine_Vod_Models_Business_VodListCdnAccessLogResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodListCdnAccessLogResult_descriptor,
        new java.lang.String[] { "Logs", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnTopAccessUrlElement_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Volcengine_Vod_Models_Business_VodCdnTopAccessUrlElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnTopAccessUrlElement_descriptor,
        new java.lang.String[] { "Url", "Pv", "Flux", });
    internal_static_Volcengine_Vod_Models_Business_VodListCdnTopAccessUrlResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Volcengine_Vod_Models_Business_VodListCdnTopAccessUrlResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodListCdnTopAccessUrlResult_descriptor,
        new java.lang.String[] { "UrlInfos", });
    internal_static_Volcengine_Vod_Models_Business_VodBandwidthData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Volcengine_Vod_Models_Business_VodBandwidthData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodBandwidthData_descriptor,
        new java.lang.String[] { "Time", "Bandwidth", });
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainBandwidthDataResult_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainBandwidthDataResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainBandwidthDataResult_descriptor,
        new java.lang.String[] { "DomainList", "StartTime", "EndTime", "Aggregation", "BandwidthType", "PeakBandwidth", "PeakBandwidthTime", "BandwidthDataList", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsData_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsData_descriptor,
        new java.lang.String[] { "Name", "Metric", "DataType", "Points", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsCommonResult_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsCommonResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnStatisticsCommonResult_descriptor,
        new java.lang.String[] { "Datas", "NoPermissionDomains", });
    internal_static_Volcengine_Vod_Models_Business_VodCdnIpInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Volcengine_Vod_Models_Business_VodCdnIpInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodCdnIpInfo_descriptor,
        new java.lang.String[] { "Ip", "CdnIp", "Location", "Isp", });
    internal_static_Volcengine_Vod_Models_Business_VodDescribeIpInfoResult_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Volcengine_Vod_Models_Business_VodDescribeIpInfoResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDescribeIpInfoResult_descriptor,
        new java.lang.String[] { "Infos", });
    internal_static_Volcengine_Vod_Models_Business_VodTrafficData_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Volcengine_Vod_Models_Business_VodTrafficData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodTrafficData_descriptor,
        new java.lang.String[] { "Time", "Traffic", });
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainTrafficDataResult_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainTrafficDataResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDescribeVodDomainTrafficDataResult_descriptor,
        new java.lang.String[] { "DomainList", "StartTime", "EndTime", "Aggregation", "TrafficType", "TotalTraffic", "TrafficDataList", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainSourceInfo_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Volcengine_Vod_Models_Business_VodDomainSourceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainSourceInfo_descriptor,
        new java.lang.String[] { "SourceStationType", "SourceStationAddressType", "Origin", "Bucket", });
    internal_static_Volcengine_Vod_Models_Business_VodDomainOriginBucketInfo_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Volcengine_Vod_Models_Business_VodDomainOriginBucketInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodDomainOriginBucketInfo_descriptor,
        new java.lang.String[] { "BucketName", "BucketSourceType", "BucketRegion", });
    internal_static_Volcengine_Vod_Models_Business_VodSubmitBlockTasksResult_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Volcengine_Vod_Models_Business_VodSubmitBlockTasksResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodSubmitBlockTasksResult_descriptor,
        new java.lang.String[] { "TaskID", });
    internal_static_Volcengine_Vod_Models_Business_VodGetContentBlockTasksResult_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Volcengine_Vod_Models_Business_VodGetContentBlockTasksResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_VodGetContentBlockTasksResult_descriptor,
        new java.lang.String[] { "Total", "PageNum", "PageSize", "Data", });
    internal_static_Volcengine_Vod_Models_Business_ContentTask_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Volcengine_Vod_Models_Business_ContentTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Business_ContentTask_descriptor,
        new java.lang.String[] { "Url", "Status", "TaskType", "CreateTime", "TaskID", });
    com.volcengine.service.vod.model.business.VodCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
