// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/business/vod_cdn.proto

package com.volcengine.service.vod.model.business;

/**
 * Protobuf type {@code Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult}
 */
public final class VodDescribeDomainConfigResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult)
    VodDescribeDomainConfigResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VodDescribeDomainConfigResult.newBuilder() to construct.
  private VodDescribeDomainConfigResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VodDescribeDomainConfigResult() {
    spaceName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VodDescribeDomainConfigResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VodDescribeDomainConfigResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            spaceName_ = s;
            break;
          }
          case 18: {
            com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder subBuilder = null;
            if (domain_ != null) {
              subBuilder = domain_.toBuilder();
            }
            domain_ = input.readMessage(com.volcengine.service.vod.model.business.VodDomainBasicInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(domain_);
              domain_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.volcengine.service.vod.model.business.VodDomainConfig.Builder subBuilder = null;
            if (config_ != null) {
              subBuilder = config_.toBuilder();
            }
            config_ = input.readMessage(com.volcengine.service.vod.model.business.VodDomainConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(config_);
              config_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.volcengine.service.vod.model.business.VodCdn.internal_static_Volcengine_Vod_Models_Business_VodDescribeDomainConfigResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.volcengine.service.vod.model.business.VodCdn.internal_static_Volcengine_Vod_Models_Business_VodDescribeDomainConfigResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.class, com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.Builder.class);
  }

  public static final int SPACENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object spaceName_;
  /**
   * <pre>
   * 点播空间名称
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  @java.lang.Override
  public java.lang.String getSpaceName() {
    java.lang.Object ref = spaceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      spaceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 点播空间名称
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpaceNameBytes() {
    java.lang.Object ref = spaceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      spaceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAIN_FIELD_NUMBER = 2;
  private com.volcengine.service.vod.model.business.VodDomainBasicInfo domain_;
  /**
   * <pre>
   * 域名基础信息。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
   * @return Whether the domain field is set.
   */
  @java.lang.Override
  public boolean hasDomain() {
    return domain_ != null;
  }
  /**
   * <pre>
   * 域名基础信息。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
   * @return The domain.
   */
  @java.lang.Override
  public com.volcengine.service.vod.model.business.VodDomainBasicInfo getDomain() {
    return domain_ == null ? com.volcengine.service.vod.model.business.VodDomainBasicInfo.getDefaultInstance() : domain_;
  }
  /**
   * <pre>
   * 域名基础信息。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
   */
  @java.lang.Override
  public com.volcengine.service.vod.model.business.VodDomainBasicInfoOrBuilder getDomainOrBuilder() {
    return getDomain();
  }

  public static final int CONFIG_FIELD_NUMBER = 3;
  private com.volcengine.service.vod.model.business.VodDomainConfig config_;
  /**
   * <pre>
   * 域名配置详情。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return config_ != null;
  }
  /**
   * <pre>
   * 域名配置详情。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
   * @return The config.
   */
  @java.lang.Override
  public com.volcengine.service.vod.model.business.VodDomainConfig getConfig() {
    return config_ == null ? com.volcengine.service.vod.model.business.VodDomainConfig.getDefaultInstance() : config_;
  }
  /**
   * <pre>
   * 域名配置详情。
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
   */
  @java.lang.Override
  public com.volcengine.service.vod.model.business.VodDomainConfigOrBuilder getConfigOrBuilder() {
    return getConfig();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(spaceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, spaceName_);
    }
    if (domain_ != null) {
      output.writeMessage(2, getDomain());
    }
    if (config_ != null) {
      output.writeMessage(3, getConfig());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(spaceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, spaceName_);
    }
    if (domain_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDomain());
    }
    if (config_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getConfig());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult)) {
      return super.equals(obj);
    }
    com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult other = (com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult) obj;

    if (!getSpaceName()
        .equals(other.getSpaceName())) return false;
    if (hasDomain() != other.hasDomain()) return false;
    if (hasDomain()) {
      if (!getDomain()
          .equals(other.getDomain())) return false;
    }
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SPACENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSpaceName().hashCode();
    if (hasDomain()) {
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
    }
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult)
      com.volcengine.service.vod.model.business.VodDescribeDomainConfigResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.volcengine.service.vod.model.business.VodCdn.internal_static_Volcengine_Vod_Models_Business_VodDescribeDomainConfigResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.volcengine.service.vod.model.business.VodCdn.internal_static_Volcengine_Vod_Models_Business_VodDescribeDomainConfigResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.class, com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.Builder.class);
    }

    // Construct using com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      spaceName_ = "";

      if (domainBuilder_ == null) {
        domain_ = null;
      } else {
        domain_ = null;
        domainBuilder_ = null;
      }
      if (configBuilder_ == null) {
        config_ = null;
      } else {
        config_ = null;
        configBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.volcengine.service.vod.model.business.VodCdn.internal_static_Volcengine_Vod_Models_Business_VodDescribeDomainConfigResult_descriptor;
    }

    @java.lang.Override
    public com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult getDefaultInstanceForType() {
      return com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult build() {
      com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult buildPartial() {
      com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult result = new com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult(this);
      result.spaceName_ = spaceName_;
      if (domainBuilder_ == null) {
        result.domain_ = domain_;
      } else {
        result.domain_ = domainBuilder_.build();
      }
      if (configBuilder_ == null) {
        result.config_ = config_;
      } else {
        result.config_ = configBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult) {
        return mergeFrom((com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult other) {
      if (other == com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult.getDefaultInstance()) return this;
      if (!other.getSpaceName().isEmpty()) {
        spaceName_ = other.spaceName_;
        onChanged();
      }
      if (other.hasDomain()) {
        mergeDomain(other.getDomain());
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object spaceName_ = "";
    /**
     * <pre>
     * 点播空间名称
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return The spaceName.
     */
    public java.lang.String getSpaceName() {
      java.lang.Object ref = spaceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        spaceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 点播空间名称
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return The bytes for spaceName.
     */
    public com.google.protobuf.ByteString
        getSpaceNameBytes() {
      java.lang.Object ref = spaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 点播空间名称
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @param value The spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      spaceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点播空间名称
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpaceName() {
      
      spaceName_ = getDefaultInstance().getSpaceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点播空间名称
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @param value The bytes for spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      spaceName_ = value;
      onChanged();
      return this;
    }

    private com.volcengine.service.vod.model.business.VodDomainBasicInfo domain_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.volcengine.service.vod.model.business.VodDomainBasicInfo, com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder, com.volcengine.service.vod.model.business.VodDomainBasicInfoOrBuilder> domainBuilder_;
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     * @return Whether the domain field is set.
     */
    public boolean hasDomain() {
      return domainBuilder_ != null || domain_ != null;
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     * @return The domain.
     */
    public com.volcengine.service.vod.model.business.VodDomainBasicInfo getDomain() {
      if (domainBuilder_ == null) {
        return domain_ == null ? com.volcengine.service.vod.model.business.VodDomainBasicInfo.getDefaultInstance() : domain_;
      } else {
        return domainBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public Builder setDomain(com.volcengine.service.vod.model.business.VodDomainBasicInfo value) {
      if (domainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        domain_ = value;
        onChanged();
      } else {
        domainBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public Builder setDomain(
        com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder builderForValue) {
      if (domainBuilder_ == null) {
        domain_ = builderForValue.build();
        onChanged();
      } else {
        domainBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public Builder mergeDomain(com.volcengine.service.vod.model.business.VodDomainBasicInfo value) {
      if (domainBuilder_ == null) {
        if (domain_ != null) {
          domain_ =
            com.volcengine.service.vod.model.business.VodDomainBasicInfo.newBuilder(domain_).mergeFrom(value).buildPartial();
        } else {
          domain_ = value;
        }
        onChanged();
      } else {
        domainBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public Builder clearDomain() {
      if (domainBuilder_ == null) {
        domain_ = null;
        onChanged();
      } else {
        domain_ = null;
        domainBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder getDomainBuilder() {
      
      onChanged();
      return getDomainFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    public com.volcengine.service.vod.model.business.VodDomainBasicInfoOrBuilder getDomainOrBuilder() {
      if (domainBuilder_ != null) {
        return domainBuilder_.getMessageOrBuilder();
      } else {
        return domain_ == null ?
            com.volcengine.service.vod.model.business.VodDomainBasicInfo.getDefaultInstance() : domain_;
      }
    }
    /**
     * <pre>
     * 域名基础信息。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainBasicInfo Domain = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.volcengine.service.vod.model.business.VodDomainBasicInfo, com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder, com.volcengine.service.vod.model.business.VodDomainBasicInfoOrBuilder> 
        getDomainFieldBuilder() {
      if (domainBuilder_ == null) {
        domainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.volcengine.service.vod.model.business.VodDomainBasicInfo, com.volcengine.service.vod.model.business.VodDomainBasicInfo.Builder, com.volcengine.service.vod.model.business.VodDomainBasicInfoOrBuilder>(
                getDomain(),
                getParentForChildren(),
                isClean());
        domain_ = null;
      }
      return domainBuilder_;
    }

    private com.volcengine.service.vod.model.business.VodDomainConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.volcengine.service.vod.model.business.VodDomainConfig, com.volcengine.service.vod.model.business.VodDomainConfig.Builder, com.volcengine.service.vod.model.business.VodDomainConfigOrBuilder> configBuilder_;
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return configBuilder_ != null || config_ != null;
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     * @return The config.
     */
    public com.volcengine.service.vod.model.business.VodDomainConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? com.volcengine.service.vod.model.business.VodDomainConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public Builder setConfig(com.volcengine.service.vod.model.business.VodDomainConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public Builder setConfig(
        com.volcengine.service.vod.model.business.VodDomainConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public Builder mergeConfig(com.volcengine.service.vod.model.business.VodDomainConfig value) {
      if (configBuilder_ == null) {
        if (config_ != null) {
          config_ =
            com.volcengine.service.vod.model.business.VodDomainConfig.newBuilder(config_).mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        configBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        config_ = null;
        onChanged();
      } else {
        config_ = null;
        configBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public com.volcengine.service.vod.model.business.VodDomainConfig.Builder getConfigBuilder() {
      
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    public com.volcengine.service.vod.model.business.VodDomainConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            com.volcengine.service.vod.model.business.VodDomainConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <pre>
     * 域名配置详情。
     * </pre>
     *
     * <code>.Volcengine.Vod.Models.Business.VodDomainConfig Config = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.volcengine.service.vod.model.business.VodDomainConfig, com.volcengine.service.vod.model.business.VodDomainConfig.Builder, com.volcengine.service.vod.model.business.VodDomainConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.volcengine.service.vod.model.business.VodDomainConfig, com.volcengine.service.vod.model.business.VodDomainConfig.Builder, com.volcengine.service.vod.model.business.VodDomainConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult)
  }

  // @@protoc_insertion_point(class_scope:Volcengine.Vod.Models.Business.VodDescribeDomainConfigResult)
  private static final com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult();
  }

  public static com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VodDescribeDomainConfigResult>
      PARSER = new com.google.protobuf.AbstractParser<VodDescribeDomainConfigResult>() {
    @java.lang.Override
    public VodDescribeDomainConfigResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VodDescribeDomainConfigResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VodDescribeDomainConfigResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VodDescribeDomainConfigResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.volcengine.service.vod.model.business.VodDescribeDomainConfigResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

