// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_cdn.proto

package com.volcengine.service.vod.model.business;

public interface VodDomainSourceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.VodDomainSourceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *源站类型
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationType SourceStationType = 1;</code>
   * @return The enum numeric value on the wire for sourceStationType.
   */
  int getSourceStationTypeValue();
  /**
   * <pre>
   *源站类型
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationType SourceStationType = 1;</code>
   * @return The sourceStationType.
   */
  com.volcengine.service.vod.model.business.VodDomainSourceStationType getSourceStationType();

  /**
   * <pre>
   *源站地址类型
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 2;</code>
   * @return The enum numeric value on the wire for sourceStationAddressType.
   */
  int getSourceStationAddressTypeValue();
  /**
   * <pre>
   *源站地址类型
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 2;</code>
   * @return The sourceStationAddressType.
   */
  com.volcengine.service.vod.model.business.VodDomainSourceStationAddressType getSourceStationAddressType();

  /**
   * <pre>
   *回源地址
   * </pre>
   *
   * <code>string Origin = 3;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <pre>
   *回源地址
   * </pre>
   *
   * <code>string Origin = 3;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <pre>
   *回源存储桶信息
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainOriginBucketInfo Bucket = 4;</code>
   * @return Whether the bucket field is set.
   */
  boolean hasBucket();
  /**
   * <pre>
   *回源存储桶信息
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainOriginBucketInfo Bucket = 4;</code>
   * @return The bucket.
   */
  com.volcengine.service.vod.model.business.VodDomainOriginBucketInfo getBucket();
  /**
   * <pre>
   *回源存储桶信息
   * </pre>
   *
   * <code>.Volcengine.Vod.Models.Business.VodDomainOriginBucketInfo Bucket = 4;</code>
   */
  com.volcengine.service.vod.model.business.VodDomainOriginBucketInfoOrBuilder getBucketOrBuilder();
}
