// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/business/vod_media.proto

package com.volcengine.service.vod.model.business;

public interface VodGetMediaEntityListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Vod.Models.Business.VodGetMediaEntityListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *符合条件的结果总数
   * </pre>
   *
   * <code>int32 TotalCount = 1;</code>
   * @return The totalCount.
   */
  int getTotalCount();

  /**
   * <pre>
   *数据偏移量
   * </pre>
   *
   * <code>int32 PageNumber = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <pre>
   *分页大小
   * </pre>
   *
   * <code>int32 PageSize = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * 基础实体信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Vod.Models.Business.VodBaseMediaEntity BaseEntityInfos = 4;</code>
   */
  java.util.List<com.volcengine.service.vod.model.business.VodBaseMediaEntity> 
      getBaseEntityInfosList();
  /**
   * <pre>
   * 基础实体信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Vod.Models.Business.VodBaseMediaEntity BaseEntityInfos = 4;</code>
   */
  com.volcengine.service.vod.model.business.VodBaseMediaEntity getBaseEntityInfos(int index);
  /**
   * <pre>
   * 基础实体信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Vod.Models.Business.VodBaseMediaEntity BaseEntityInfos = 4;</code>
   */
  int getBaseEntityInfosCount();
  /**
   * <pre>
   * 基础实体信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Vod.Models.Business.VodBaseMediaEntity BaseEntityInfos = 4;</code>
   */
  java.util.List<? extends com.volcengine.service.vod.model.business.VodBaseMediaEntityOrBuilder> 
      getBaseEntityInfosOrBuilderList();
  /**
   * <pre>
   * 基础实体信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Vod.Models.Business.VodBaseMediaEntity BaseEntityInfos = 4;</code>
   */
  com.volcengine.service.vod.model.business.VodBaseMediaEntityOrBuilder getBaseEntityInfosOrBuilder(
      int index);
}
