// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.volcengine.model.maas;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Base.rawBody);
    registry.add(Base.query);
    registry.add(Base.header);
    registry.add(Base.cookie);
    registry.add(Base.body);
    registry.add(Base.path);
    registry.add(Base.vd);
    registry.add(Base.form);
    registry.add(Base.goTag);
    registry.add(Base.jsConv);
    registry.add(Base.get);
    registry.add(Base.post);
    registry.add(Base.put);
    registry.add(Base.delete);
    registry.add(Base.patch);
    registry.add(Base.options);
    registry.add(Base.head);
    registry.add(Base.any);
    registry.add(Base.genPath);
    registry.add(Base.apiVersion);
    registry.add(Base.tag);
    registry.add(Base.name);
    registry.add(Base.apiLevel);
    registry.add(Base.serializer);
    registry.add(Base.param);
    registry.add(Base.baseurl);
    registry.add(Base.httpCode);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int RAW_BODY_FIELD_NUMBER = 50101;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> rawBody = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int QUERY_FIELD_NUMBER = 50102;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> query = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HEADER_FIELD_NUMBER = 50103;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> header = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int COOKIE_FIELD_NUMBER = 50104;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> cookie = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BODY_FIELD_NUMBER = 50105;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> body = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PATH_FIELD_NUMBER = 50106;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> path = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int VD_FIELD_NUMBER = 50107;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> vd = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FORM_FIELD_NUMBER = 50108;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> form = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GO_TAG_FIELD_NUMBER = 51001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> goTag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int JS_CONV_FIELD_NUMBER = 50109;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> jsConv = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GET_FIELD_NUMBER = 50201;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> get = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int POST_FIELD_NUMBER = 50202;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> post = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PUT_FIELD_NUMBER = 50203;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> put = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DELETE_FIELD_NUMBER = 50204;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> delete = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PATCH_FIELD_NUMBER = 50205;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> patch = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONS_FIELD_NUMBER = 50206;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> options = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HEAD_FIELD_NUMBER = 50207;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> head = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ANY_FIELD_NUMBER = 50208;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> any = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GEN_PATH_FIELD_NUMBER = 50301;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> genPath = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int API_VERSION_FIELD_NUMBER = 50302;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> apiVersion = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TAG_FIELD_NUMBER = 50303;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> tag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NAME_FIELD_NUMBER = 50304;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> name = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int API_LEVEL_FIELD_NUMBER = 50305;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> apiLevel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERIALIZER_FIELD_NUMBER = 50306;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> serializer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PARAM_FIELD_NUMBER = 50307;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> param = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BASEURL_FIELD_NUMBER = 50308;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> baseurl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HTTP_CODE_FIELD_NUMBER = 50401;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Integer> httpCode = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\022\003api\032 google/protobuf/descr" +
      "iptor.proto:1\n\010raw_body\022\035.google.protobu" +
      "f.FieldOptions\030\265\207\003 \001(\t:.\n\005query\022\035.google" +
      ".protobuf.FieldOptions\030\266\207\003 \001(\t:/\n\006header" +
      "\022\035.google.protobuf.FieldOptions\030\267\207\003 \001(\t:" +
      "/\n\006cookie\022\035.google.protobuf.FieldOptions" +
      "\030\270\207\003 \001(\t:-\n\004body\022\035.google.protobuf.Field" +
      "Options\030\271\207\003 \001(\t:-\n\004path\022\035.google.protobu" +
      "f.FieldOptions\030\272\207\003 \001(\t:+\n\002vd\022\035.google.pr" +
      "otobuf.FieldOptions\030\273\207\003 \001(\t:-\n\004form\022\035.go" +
      "ogle.protobuf.FieldOptions\030\274\207\003 \001(\t:/\n\006go" +
      "_tag\022\035.google.protobuf.FieldOptions\030\271\216\003 " +
      "\001(\t:0\n\007js_conv\022\035.google.protobuf.FieldOp" +
      "tions\030\275\207\003 \001(\t:-\n\003get\022\036.google.protobuf.M" +
      "ethodOptions\030\231\210\003 \001(\t:.\n\004post\022\036.google.pr" +
      "otobuf.MethodOptions\030\232\210\003 \001(\t:-\n\003put\022\036.go" +
      "ogle.protobuf.MethodOptions\030\233\210\003 \001(\t:0\n\006d" +
      "elete\022\036.google.protobuf.MethodOptions\030\234\210" +
      "\003 \001(\t:/\n\005patch\022\036.google.protobuf.MethodO" +
      "ptions\030\235\210\003 \001(\t:1\n\007options\022\036.google.proto" +
      "buf.MethodOptions\030\236\210\003 \001(\t:.\n\004head\022\036.goog" +
      "le.protobuf.MethodOptions\030\237\210\003 \001(\t:-\n\003any" +
      "\022\036.google.protobuf.MethodOptions\030\240\210\003 \001(\t" +
      ":2\n\010gen_path\022\036.google.protobuf.MethodOpt" +
      "ions\030\375\210\003 \001(\t:5\n\013api_version\022\036.google.pro" +
      "tobuf.MethodOptions\030\376\210\003 \001(\t:-\n\003tag\022\036.goo" +
      "gle.protobuf.MethodOptions\030\377\210\003 \001(\t:.\n\004na" +
      "me\022\036.google.protobuf.MethodOptions\030\200\211\003 \001" +
      "(\t:3\n\tapi_level\022\036.google.protobuf.Method" +
      "Options\030\201\211\003 \001(\t:4\n\nserializer\022\036.google.p" +
      "rotobuf.MethodOptions\030\202\211\003 \001(\t:/\n\005param\022\036" +
      ".google.protobuf.MethodOptions\030\203\211\003 \001(\t:1" +
      "\n\007baseurl\022\036.google.protobuf.MethodOption" +
      "s\030\204\211\003 \001(\t:6\n\thttp_code\022!.google.protobuf" +
      ".EnumValueOptions\030\341\211\003 \001(\005B*\n\"com.volceng" +
      "ine.service.maas.modelsZ\004/api"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    rawBody.internalInit(descriptor.getExtensions().get(0));
    query.internalInit(descriptor.getExtensions().get(1));
    header.internalInit(descriptor.getExtensions().get(2));
    cookie.internalInit(descriptor.getExtensions().get(3));
    body.internalInit(descriptor.getExtensions().get(4));
    path.internalInit(descriptor.getExtensions().get(5));
    vd.internalInit(descriptor.getExtensions().get(6));
    form.internalInit(descriptor.getExtensions().get(7));
    goTag.internalInit(descriptor.getExtensions().get(8));
    jsConv.internalInit(descriptor.getExtensions().get(9));
    get.internalInit(descriptor.getExtensions().get(10));
    post.internalInit(descriptor.getExtensions().get(11));
    put.internalInit(descriptor.getExtensions().get(12));
    delete.internalInit(descriptor.getExtensions().get(13));
    patch.internalInit(descriptor.getExtensions().get(14));
    options.internalInit(descriptor.getExtensions().get(15));
    head.internalInit(descriptor.getExtensions().get(16));
    any.internalInit(descriptor.getExtensions().get(17));
    genPath.internalInit(descriptor.getExtensions().get(18));
    apiVersion.internalInit(descriptor.getExtensions().get(19));
    tag.internalInit(descriptor.getExtensions().get(20));
    name.internalInit(descriptor.getExtensions().get(21));
    apiLevel.internalInit(descriptor.getExtensions().get(22));
    serializer.internalInit(descriptor.getExtensions().get(23));
    param.internalInit(descriptor.getExtensions().get(24));
    baseurl.internalInit(descriptor.getExtensions().get(25));
    httpCode.internalInit(descriptor.getExtensions().get(26));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
