// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/response/response_vod.proto

package com.volcengine.service.vod.model.response;

public final class VodResponse {
  private VodResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAllPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetOriginalPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUploadMediaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUploadMediaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodQueryUploadTaskInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUrlUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUrlUploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodApplyUploadInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCommitUploadInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaInfosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetMediaInfosResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetRecommendedPosterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaStorageClassResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDeleteTranscodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaTosFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaTosFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetMediaListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetSubtitleInfoListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAuditFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetMLFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetBetterFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAudioInfoForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCreateVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDeleteVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListVideoClassificationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListSnapshotsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetFileListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetFileListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodExtractMediaMetaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodStartWorkflowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodStartWorkflowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodRetrieveTranscodeResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListWorkflowExecutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditProgressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCreateSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCreateSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetSpaceDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListDomainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListDomainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListCdnTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListCdnAccessLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodListCdnTopAccessUrlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCdnStatisticsCommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDescribeIPInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetContentBlockTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodCreateDomainV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodCreateDomainV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainExpireV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodAddCallbackSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodSetCallbackEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodSetCallbackEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodGetAppInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodGetAppInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSnapshotDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Response_VodQueryMediaBlockStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*volcengine/vod/response/response_vod.p" +
      "roto\022\036Volcengine.Vod.Models.Response\032\032vo" +
      "lcengine/base/base.proto\032&volcengine/vod" +
      "/business/vod_play.proto\032\'volcengine/vod" +
      "/business/vod_media.proto\032(volcengine/vo" +
      "d/business/vod_upload.proto\032*volcengine/" +
      "vod/business/vod_workflow.proto\032&volceng" +
      "ine/vod/business/vod_edit.proto\032\'volceng" +
      "ine/vod/business/vod_space.proto\032%volcen" +
      "gine/vod/business/vod_cdn.proto\032(volceng" +
      "ine/vod/business/vod_common.proto\0320volce" +
      "ngine/vod/business/vod_smart_strategy.pr" +
      "oto\032-volcengine/vod/business/vod_apps_ma" +
      "nage.proto\032)volcengine/vod/business/vod_" +
      "measure.proto\"\252\001\n\031VodGetAllPlayInfoRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\022D\n\006" +
      "Result\030\002 \001(\01324.Volcengine.Vod.Models.Bus" +
      "iness.VodAllPlayInfoResult\"\243\001\n\026VodGetPla" +
      "yInfoResponse\022G\n\020ResponseMetadata\030\001 \001(\0132" +
      "-.Volcengine.Base.Models.Base.ResponseMe" +
      "tadata\022@\n\006Result\030\002 \001(\01320.Volcengine.Vod." +
      "Models.Business.VodPlayInfoModel\"\267\001\n\036Vod" +
      "GetOriginalPlayInfoResponse\022G\n\020ResponseM" +
      "etadata\030\001 \001(\0132-.Volcengine.Base.Models.B" +
      "ase.ResponseMetadata\022L\n\006Result\030\002 \001(\0132<.V" +
      "olcengine.Vod.Models.Business.VodGetOrig" +
      "inalPlayInfoResult\"\273\001\n VodGetPrivateDrmP" +
      "layAuthResponse\022G\n\020ResponseMetadata\030\001 \001(" +
      "\0132-.Volcengine.Base.Models.Base.Response" +
      "Metadata\022N\n\006Result\030\002 \001(\0132>.Volcengine.Vo" +
      "d.Models.Business.VodGetPrivateDrmPlayAu" +
      "thResult\"\267\001\n\036VodGetHlsDecryptionKeyRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\022L\n\006" +
      "Result\030\002 \001(\0132<.Volcengine.Vod.Models.Bus" +
      "iness.VodGetHlsDecryptionKeyResult\"\323\001\n,V" +
      "odGetPlayInfoWithLiveTimeShiftSceneRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\022Z\n\006" +
      "Result\030\002 \001(\0132J.Volcengine.Vod.Models.Bus" +
      "iness.VodGetPlayInfoWithLiveTimeShiftSce" +
      "neResult\"\240\001\n\026VodUploadMediaResponse\022G\n\020R" +
      "esponseMetadata\030\001 \001(\0132-.Volcengine.Base." +
      "Models.Base.ResponseMetadata\022=\n\006Result\030\002" +
      " \001(\0132-.Volcengine.Vod.Models.Business.Vo" +
      "dCommitData\"\247\001\n\036VodQueryUploadTaskInfoRe" +
      "sponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volce" +
      "ngine.Base.Models.Base.ResponseMetadata\022" +
      "<\n\006Result\030\002 \001(\0132,.Volcengine.Vod.Models." +
      "Business.VodQueryData\"\243\001\n\024VodUrlUploadRe" +
      "sponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volce" +
      "ngine.Base.Models.Base.ResponseMetadata\022" +
      "B\n\006Result\030\002 \001(\01322.Volcengine.Vod.Models." +
      "Business.VodUrlResponseData\"\257\001\n\032VodApply" +
      "UploadInfoResponse\022G\n\020ResponseMetadata\030\001" +
      " \001(\0132-.Volcengine.Base.Models.Base.Respo" +
      "nseMetadata\022H\n\006Result\030\002 \001(\01328.Volcengine" +
      ".Vod.Models.Business.VodApplyUploadInfoR" +
      "esult\"\261\001\n\033VodCommitUploadInfoResponse\022G\n" +
      "\020ResponseMetadata\030\001 \001(\0132-.Volcengine.Bas" +
      "e.Models.Base.ResponseMetadata\022I\n\006Result" +
      "\030\002 \001(\01329.Volcengine.Vod.Models.Business." +
      "VodCommitUploadInfoResult\"\251\001\n\030VodGetMedi" +
      "aInfosResponse\022G\n\020ResponseMetadata\030\001 \001(\013" +
      "2-.Volcengine.Base.Models.Base.ResponseM" +
      "etadata\022D\n\006Result\030\002 \001(\01324.Volcengine.Vod" +
      ".Models.Business.VodGetMediaInfosData\"e\n" +
      "\032VodUpdateMediaInfoResponse\022G\n\020ResponseM" +
      "etadata\030\001 \001(\0132-.Volcengine.Base.Models.B" +
      "ase.ResponseMetadata\"\257\001\n\037VodGetRecommend" +
      "edPosterResponse\022G\n\020ResponseMetadata\030\001 \001" +
      "(\0132-.Volcengine.Base.Models.Base.Respons" +
      "eMetadata\022C\n\006Result\030\002 \001(\01323.Volcengine.V" +
      "od.Models.Business.VodGetRecPosterData\"n" +
      "\n#VodUpdateMediaPublishStatusResponse\022G\n" +
      "\020ResponseMetadata\030\001 \001(\0132-.Volcengine.Bas" +
      "e.Models.Base.ResponseMetadata\"\275\001\n\"VodUp" +
      "dateMediaStorageClassResponse\022G\n\020Respons" +
      "eMetadata\030\001 \001(\0132-.Volcengine.Base.Models" +
      ".Base.ResponseMetadata\022N\n\006Result\030\002 \001(\0132>" +
      ".Volcengine.Vod.Models.Business.VodUpdat" +
      "eMediaStorageClassData\"\245\001\n\026VodDeleteMedi" +
      "aResponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Vo" +
      "lcengine.Base.Models.Base.ResponseMetada" +
      "ta\022B\n\006Result\030\002 \001(\01322.Volcengine.Vod.Mode" +
      "ls.Business.VodDeleteMediaData\"\257\001\n\033VodDe" +
      "leteTranscodesResponse\022G\n\020ResponseMetada" +
      "ta\030\001 \001(\0132-.Volcengine.Base.Models.Base.R" +
      "esponseMetadata\022G\n\006Result\030\002 \001(\01327.Volcen" +
      "gine.Vod.Models.Business.VodDeleteTransc" +
      "odesData\"\263\001\n\035VodDeleteMediaTosFileRespon" +
      "se\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengin" +
      "e.Base.Models.Base.ResponseMetadata\022I\n\006R" +
      "esult\030\002 \001(\01329.Volcengine.Vod.Models.Busi" +
      "ness.VodDeleteMediaTosFileData\"\247\001\n\027VodGe" +
      "tMediaListResponse\022G\n\020ResponseMetadata\030\001" +
      " \001(\0132-.Volcengine.Base.Models.Base.Respo" +
      "nseMetadata\022C\n\006Result\030\002 \001(\01323.Volcengine" +
      ".Vod.Models.Business.VodGetMediaListData" +
      "\"\265\001\n\036VodGetSubtitleInfoListResponse\022G\n\020R" +
      "esponseMetadata\030\001 \001(\0132-.Volcengine.Base." +
      "Models.Base.ResponseMetadata\022J\n\006Result\030\002" +
      " \001(\0132:.Volcengine.Vod.Models.Business.Vo" +
      "dGetSubtitleInfoListData\"\267\001\n\037VodUpdateSu" +
      "btitleStatusResponse\022G\n\020ResponseMetadata" +
      "\030\001 \001(\0132-.Volcengine.Base.Models.Base.Res" +
      "ponseMetadata\022K\n\006Result\030\002 \001(\0132;.Volcengi" +
      "ne.Vod.Models.Business.VodUpdateSubtitle" +
      "StatusData\"h\n\035VodUpdateSubtitleInfoRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\"\270\001\n" +
      "!VodGetAuditFramesForAuditResponse\022G\n\020Re" +
      "sponseMetadata\030\001 \001(\0132-.Volcengine.Base.M" +
      "odels.Base.ResponseMetadata\022J\n\006Result\030\002 " +
      "\001(\0132:.Volcengine.Vod.Models.Business.Vod" +
      "GetFramesForAuditResult\"\265\001\n\036VodGetMLFram" +
      "esForAuditResponse\022G\n\020ResponseMetadata\030\001" +
      " \001(\0132-.Volcengine.Base.Models.Base.Respo" +
      "nseMetadata\022J\n\006Result\030\002 \001(\0132:.Volcengine" +
      ".Vod.Models.Business.VodGetFramesForAudi" +
      "tResult\"\277\001\n\"VodGetBetterFramesForAuditRe" +
      "sponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volce" +
      "ngine.Base.Models.Base.ResponseMetadata\022" +
      "P\n\006Result\030\002 \001(\0132@.Volcengine.Vod.Models." +
      "Business.VodGetBetterFramesForAuditResul" +
      "t\"\271\001\n\037VodGetAudioInfoForAuditResponse\022G\n" +
      "\020ResponseMetadata\030\001 \001(\0132-.Volcengine.Bas" +
      "e.Models.Base.ResponseMetadata\022M\n\006Result" +
      "\030\002 \001(\0132=.Volcengine.Vod.Models.Business." +
      "VodGetAudioInfoForAuditResult\"\333\001\n0VodGet" +
      "AutomaticSpeechRecognitionForAuditRespon" +
      "se\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengin" +
      "e.Base.Models.Base.ResponseMetadata\022^\n\006R" +
      "esult\030\002 \001(\0132N.Volcengine.Vod.Models.Busi" +
      "ness.VodGetAutomaticSpeechRecognitionFor" +
      "AuditResult\"\315\001\n)VodGetAudioEventDetectio" +
      "nForAuditResponse\022G\n\020ResponseMetadata\030\001 " +
      "\001(\0132-.Volcengine.Base.Models.Base.Respon" +
      "seMetadata\022W\n\006Result\030\002 \001(\0132G.Volcengine." +
      "Vod.Models.Business.VodGetAudioEventDete" +
      "ctionForAuditResult\"\301\001\n$VodCreateVideoCl" +
      "assificationResponse\022G\n\020ResponseMetadata" +
      "\030\001 \001(\0132-.Volcengine.Base.Models.Base.Res" +
      "ponseMetadata\022P\n\006Result\030\002 \001(\0132@.Volcengi" +
      "ne.Vod.Models.Business.VodCreateVideoCla" +
      "ssificationData\"o\n$VodUpdateVideoClassif" +
      "icationResponse\022G\n\020ResponseMetadata\030\001 \001(" +
      "\0132-.Volcengine.Base.Models.Base.Response" +
      "Metadata\"o\n$VodDeleteVideoClassification" +
      "Response\022G\n\020ResponseMetadata\030\001 \001(\0132-.Vol" +
      "cengine.Base.Models.Base.ResponseMetadat" +
      "a\"\273\001\n#VodListVideoClassificationsRespons" +
      "e\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengine" +
      ".Base.Models.Base.ResponseMetadata\022K\n\006Re" +
      "sult\030\002 \001(\0132;.Volcengine.Vod.Models.Busin" +
      "ess.VodVideoClassificationsData\"\244\001\n\030VodL" +
      "istSnapshotsResponse\022G\n\020ResponseMetadata" +
      "\030\001 \001(\0132-.Volcengine.Base.Models.Base.Res" +
      "ponseMetadata\022?\n\006Result\030\002 \001(\0132/.Volcengi" +
      "ne.Vod.Models.Business.VodSnapshotData\"\247" +
      "\001\n\026VodGetFileListResponse\022G\n\020ResponseMet" +
      "adata\030\001 \001(\0132-.Volcengine.Base.Models.Bas" +
      "e.ResponseMetadata\022D\n\006Result\030\002 \001(\01324.Vol" +
      "cengine.Vod.Models.Business.VodGetMediaI" +
      "nfosData\"j\n\037VodExtractMediaMetaTaskRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\"\253\001\n" +
      "\030VodStartWorkflowResponse\022G\n\020ResponseMet" +
      "adata\030\001 \001(\0132-.Volcengine.Base.Models.Bas" +
      "e.ResponseMetadata\022F\n\006Result\030\002 \001(\01326.Vol" +
      "cengine.Vod.Models.Business.VodStartWork" +
      "flowResult\"\256\001\n\"VodRetrieveTranscodeResul" +
      "tResponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Vo" +
      "lcengine.Base.Models.Base.ResponseMetada" +
      "ta\022?\n\006Result\030\002 \001(\0132/.Volcengine.Vod.Mode" +
      "ls.Business.TranscodeResult\"\273\001\n VodListW" +
      "orkflowExecutionResponse\022G\n\020ResponseMeta" +
      "data\030\001 \001(\0132-.Volcengine.Base.Models.Base" +
      ".ResponseMetadata\022N\n\006Result\030\002 \001(\0132>.Volc" +
      "engine.Vod.Models.Business.VodListWorkfl" +
      "owExecutionResult\"\305\001\n%VodGetWorkflowExec" +
      "utionDetailResponse\022G\n\020ResponseMetadata\030" +
      "\001 \001(\0132-.Volcengine.Base.Models.Base.Resp" +
      "onseMetadata\022S\n\006Result\030\002 \001(\0132C.Volcengin" +
      "e.Vod.Models.Business.VodGetWorkflowExec" +
      "utionDetailResult\"\263\001\n%VodGetWorkflowExec" +
      "utionStatusResponse\022G\n\020ResponseMetadata\030" +
      "\001 \001(\0132-.Volcengine.Base.Models.Base.Resp" +
      "onseMetadata\022A\n\006Result\030\002 \001(\01321.Volcengin" +
      "e.Vod.Models.Business.WorkflowExecution\"" +
      "\252\001\n\034VodGetWorkflowResultResponse\022G\n\020Resp" +
      "onseMetadata\030\001 \001(\0132-.Volcengine.Base.Mod" +
      "els.Base.ResponseMetadata\022A\n\006Result\030\002 \001(" +
      "\01321.Volcengine.Vod.Models.Business.VodWo" +
      "rkflowResult\"\300\001\n$VodSubmitDirectEditTask" +
      "AsyncResponse\022G\n\020ResponseMetadata\030\001 \001(\0132" +
      "-.Volcengine.Base.Models.Base.ResponseMe" +
      "tadata\022O\n\006Result\030\002 \001(\0132?.Volcengine.Vod." +
      "Models.Business.SubmitDirectEditTaskAsyn" +
      "cResult\"\262\001\n VodGetDirectEditProgressResp" +
      "onse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volceng" +
      "ine.Base.Models.Base.ResponseMetadata\022E\n" +
      "\006Result\030\002 \001(\01325.Volcengine.Vod.Models.Bu" +
      "siness.GetDirectEditProgress\"\256\001\n\036VodGetD" +
      "irectEditResultResponse\022G\n\020ResponseMetad" +
      "ata\030\001 \001(\0132-.Volcengine.Base.Models.Base." +
      "ResponseMetadata\022C\n\006Result\030\002 \003(\01323.Volce" +
      "ngine.Vod.Models.Business.GetDirectEditR" +
      "esult\"a\n\026VodCreateSpaceResponse\022G\n\020Respo" +
      "nseMetadata\030\001 \001(\0132-.Volcengine.Base.Mode" +
      "ls.Base.ResponseMetadata\"\235\001\n\024VodListSpac" +
      "eResponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Vo" +
      "lcengine.Base.Models.Base.ResponseMetada" +
      "ta\022<\n\006Result\030\002 \003(\0132,.Volcengine.Vod.Mode" +
      "ls.Business.VodSpaceInfo\"\242\001\n\031VodGetSpace" +
      "DetailResponse\022G\n\020ResponseMetadata\030\001 \001(\013" +
      "2-.Volcengine.Base.Models.Base.ResponseM" +
      "etadata\022<\n\006Result\030\002 \001(\0132,.Volcengine.Vod" +
      ".Models.Business.VodSpaceInfo\"a\n\026VodUpda" +
      "teSpaceResponse\022G\n\020ResponseMetadata\030\001 \001(" +
      "\0132-.Volcengine.Base.Models.Base.Response" +
      "Metadata\"m\n\"VodUpdateSpaceUploadConfigRe" +
      "sponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volce" +
      "ngine.Base.Models.Base.ResponseMetadata\"" +
      "\307\001\n&VodDescribeVodSpaceStorageDataRespon" +
      "se\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengin" +
      "e.Base.Models.Base.ResponseMetadata\022T\n\006R" +
      "esult\030\002 \001(\0132D.Volcengine.Vod.Models.Busi" +
      "ness.VodDescribeVodSpaceStorageDataResul" +
      "t\"\245\001\n\025VodListDomainResponse\022G\n\020ResponseM" +
      "etadata\030\001 \001(\0132-.Volcengine.Base.Models.B" +
      "ase.ResponseMetadata\022C\n\006Result\030\002 \001(\01323.V" +
      "olcengine.Vod.Models.Business.VodDomainC" +
      "onfigInfo\"\262\001\n\037VodCreateCdnRefreshTaskRes" +
      "ponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcen" +
      "gine.Base.Models.Base.ResponseMetadata\022F" +
      "\n\006Result\030\002 \001(\01326.Volcengine.Vod.Models.B" +
      "usiness.VodCreateCdnTaskResult\"\262\001\n\037VodCr" +
      "eateCdnPreloadTaskResponse\022G\n\020ResponseMe" +
      "tadata\030\001 \001(\0132-.Volcengine.Base.Models.Ba" +
      "se.ResponseMetadata\022F\n\006Result\030\002 \001(\01326.Vo" +
      "lcengine.Vod.Models.Business.VodCreateCd" +
      "nTaskResult\"\244\001\n\027VodListCdnTasksResponse\022" +
      "G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengine.B" +
      "ase.Models.Base.ResponseMetadata\022@\n\006Resu" +
      "lt\030\002 \001(\01320.Volcengine.Vod.Models.Busines" +
      "s.VodCdnTaskResult\"\261\001\n\033VodListCdnAccessL" +
      "ogResponse\022G\n\020ResponseMetadata\030\001 \001(\0132-.V" +
      "olcengine.Base.Models.Base.ResponseMetad" +
      "ata\022I\n\006Result\030\002 \001(\01329.Volcengine.Vod.Mod" +
      "els.Business.VodListCdnAccessLogResult\"\267" +
      "\001\n\036VodListCdnTopAccessUrlResponse\022G\n\020Res" +
      "ponseMetadata\030\001 \001(\0132-.Volcengine.Base.Mo" +
      "dels.Base.ResponseMetadata\022L\n\006Result\030\002 \001" +
      "(\0132<.Volcengine.Vod.Models.Business.VodL" +
      "istCdnTopAccessUrlResult\"\315\001\n)VodDescribe" +
      "VodDomainBandwidthDataResponse\022G\n\020Respon" +
      "seMetadata\030\001 \001(\0132-.Volcengine.Base.Model" +
      "s.Base.ResponseMetadata\022W\n\006Result\030\002 \001(\0132" +
      "G.Volcengine.Vod.Models.Business.VodDesc" +
      "ribeVodDomainBandwidthDataResult\"\267\001\n\036Vod" +
      "CdnStatisticsCommonResponse\022G\n\020ResponseM" +
      "etadata\030\001 \001(\0132-.Volcengine.Base.Models.B" +
      "ase.ResponseMetadata\022L\n\006Result\030\002 \001(\0132<.V" +
      "olcengine.Vod.Models.Business.VodCdnStat" +
      "isticsCommonResult\"\242\001\n\031VodDescribeIPInfo" +
      "Response\022G\n\020ResponseMetadata\030\001 \001(\0132-.Vol" +
      "cengine.Base.Models.Base.ResponseMetadat" +
      "a\022<\n\006Result\030\002 \003(\0132,.Volcengine.Vod.Model" +
      "s.Business.VodCdnIpInfo\"\311\001\n\'VodDescribeV" +
      "odDomainTrafficDataResponse\022G\n\020ResponseM" +
      "etadata\030\001 \001(\0132-.Volcengine.Base.Models.B" +
      "ase.ResponseMetadata\022U\n\006Result\030\002 \001(\0132E.V" +
      "olcengine.Vod.Models.Business.VodDescrib" +
      "eVodDomainTrafficDataResult\"\261\001\n\033VodSubmi" +
      "tBlockTasksResponse\022G\n\020ResponseMetadata\030" +
      "\001 \001(\0132-.Volcengine.Base.Models.Base.Resp" +
      "onseMetadata\022I\n\006Result\030\002 \001(\01329.Volcengin" +
      "e.Vod.Models.Business.VodSubmitBlockTask" +
      "sResult\"\271\001\n\037VodGetContentBlockTasksRespo" +
      "nse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengi" +
      "ne.Base.Models.Base.ResponseMetadata\022M\n\006" +
      "Result\030\002 \001(\0132=.Volcengine.Vod.Models.Bus" +
      "iness.VodGetContentBlockTasksResult\"d\n\031V" +
      "odCreateDomainV2Response\022G\n\020ResponseMeta" +
      "data\030\001 \001(\0132-.Volcengine.Base.Models.Base" +
      ".ResponseMetadata\"j\n\037VodUpdateDomainExpi" +
      "reV2Response\022G\n\020ResponseMetadata\030\001 \001(\0132-" +
      ".Volcengine.Base.Models.Base.ResponseMet" +
      "adata\"n\n#VodUpdateDomainAuthConfigV2Resp" +
      "onse\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volceng" +
      "ine.Base.Models.Base.ResponseMetadata\"m\n" +
      "\"VodAddCallbackSubscriptionResponse\022G\n\020R" +
      "esponseMetadata\030\001 \001(\0132-.Volcengine.Base." +
      "Models.Base.ResponseMetadata\"f\n\033VodSetCa" +
      "llbackEventResponse\022G\n\020ResponseMetadata\030" +
      "\001 \001(\0132-.Volcengine.Base.Models.Base.Resp" +
      "onseMetadata\"\311\001\n\'VodGetSmartStrategyLite" +
      "PlayInfoResponse\022G\n\020ResponseMetadata\030\001 \001" +
      "(\0132-.Volcengine.Base.Models.Base.Respons" +
      "eMetadata\022U\n\006Result\030\002 \001(\0132E.Volcengine.V" +
      "od.Models.Business.VodGetSmartStrategyLi" +
      "tePlayInfoResult\"\245\001\n\025VodGetAppInfoRespon" +
      "se\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengin" +
      "e.Base.Models.Base.ResponseMetadata\022C\n\006R" +
      "esult\030\002 \001(\01323.Volcengine.Vod.Models.Busi" +
      "ness.VodGetAppInfoResult\"\305\001\n%DescribeVod" +
      "SpaceTranscodeDataResponse\022G\n\020ResponseMe" +
      "tadata\030\001 \001(\0132-.Volcengine.Base.Models.Ba" +
      "se.ResponseMetadata\022S\n\006Result\030\002 \001(\0132C.Vo" +
      "lcengine.Vod.Models.Business.DescribeVod" +
      "SpaceTranscodeDataResult\"\303\001\n$DescribeVod" +
      "SpaceAIStatisDataResponse\022G\n\020ResponseMet" +
      "adata\030\001 \001(\0132-.Volcengine.Base.Models.Bas" +
      "e.ResponseMetadata\022R\n\006Result\030\002 \001(\0132B.Vol" +
      "cengine.Vod.Models.Business.DescribeVodS" +
      "paceAIStatisDataResult\"\317\001\n*DescribeVodSp" +
      "aceSubtitleStatisDataResponse\022G\n\020Respons" +
      "eMetadata\030\001 \001(\0132-.Volcengine.Base.Models" +
      ".Base.ResponseMetadata\022X\n\006Result\030\002 \001(\0132H" +
      ".Volcengine.Vod.Models.Business.Describe" +
      "VodSpaceSubtitleStatisDataResult\"\313\001\n(Des" +
      "cribeVodSpaceDetectStatisDataResponse\022G\n" +
      "\020ResponseMetadata\030\001 \001(\0132-.Volcengine.Bas" +
      "e.Models.Base.ResponseMetadata\022V\n\006Result" +
      "\030\002 \001(\0132F.Volcengine.Vod.Models.Business." +
      "DescribeVodSpaceDetectStatisDataResult\"\271" +
      "\001\n\037DescribeVodSnapshotDataResponse\022G\n\020Re" +
      "sponseMetadata\030\001 \001(\0132-.Volcengine.Base.M" +
      "odels.Base.ResponseMetadata\022M\n\006Result\030\002 " +
      "\001(\0132=.Volcengine.Vod.Models.Business.Des" +
      "cribeVodSnapshotDataResult\"\317\001\n*DescribeV" +
      "odSpaceWorkflowDetailDataResponse\022G\n\020Res" +
      "ponseMetadata\030\001 \001(\0132-.Volcengine.Base.Mo" +
      "dels.Base.ResponseMetadata\022X\n\006Result\030\002 \001" +
      "(\0132H.Volcengine.Vod.Models.Business.Desc" +
      "ribeVodSpaceWorkflowDetailDataResult\"\307\001\n" +
      "&DescribeVodSpaceEditDetailDataResponse\022" +
      "G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengine.B" +
      "ase.Models.Base.ResponseMetadata\022T\n\006Resu" +
      "lt\030\002 \001(\0132D.Volcengine.Vod.Models.Busines" +
      "s.DescribeVodSpaceEditDetailDataResult\"\307" +
      "\001\n&DescribeVodPlayFileLogByDomainRespons" +
      "e\022G\n\020ResponseMetadata\030\001 \001(\0132-.Volcengine" +
      ".Base.Models.Base.ResponseMetadata\022T\n\006Re" +
      "sult\030\002 \001(\0132D.Volcengine.Vod.Models.Busin" +
      "ess.DescribeVodPlayFileLogByDomainResult" +
      "\"\271\001\n\037VodSubmitBlockMediaTaskResponse\022G\n\020" +
      "ResponseMetadata\030\001 \001(\0132-.Volcengine.Base" +
      ".Models.Base.ResponseMetadata\022M\n\006Result\030" +
      "\002 \001(\0132=.Volcengine.Vod.Models.Business.V" +
      "odSubmitBlockMediaTaskResult\"\275\001\n!VodSubm" +
      "itUnblockMediaTaskResponse\022G\n\020ResponseMe" +
      "tadata\030\001 \001(\0132-.Volcengine.Base.Models.Ba" +
      "se.ResponseMetadata\022O\n\006Result\030\002 \001(\0132?.Vo" +
      "lcengine.Vod.Models.Business.VodSubmitUn" +
      "blockMediaTaskResult\"\273\001\n VodQueryMediaBl" +
      "ockStatusResponse\022G\n\020ResponseMetadata\030\001 " +
      "\001(\0132-.Volcengine.Base.Models.Base.Respon" +
      "seMetadata\022N\n\006Result\030\002 \001(\0132>.Volcengine." +
      "Vod.Models.Business.VodQueryMediaBlockSt" +
      "atusResultB\314\001\n)com.volcengine.service.vo" +
      "d.model.responseB\013VodResponseP\001ZAgithub." +
      "com/volcengine/volc-sdk-golang/service/v" +
      "od/models/response\240\001\001\330\001\001\312\002 Volc\\Service\\" +
      "Vod\\Models\\Response\342\002#Volc\\Service\\Vod\\M" +
      "odels\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.volcengine.service.base.model.base.Base.getDescriptor(),
          com.volcengine.service.vod.model.business.VodPlay.getDescriptor(),
          com.volcengine.service.vod.model.business.VodMedia.getDescriptor(),
          com.volcengine.service.vod.model.business.VodUpload.getDescriptor(),
          com.volcengine.service.vod.model.business.VodWorkflow.getDescriptor(),
          com.volcengine.service.vod.model.business.VodEdit.getDescriptor(),
          com.volcengine.service.vod.model.business.VodSpace.getDescriptor(),
          com.volcengine.service.vod.model.business.VodCdn.getDescriptor(),
          com.volcengine.service.vod.model.business.VodCommon.getDescriptor(),
          com.volcengine.service.vod.model.business.VodSmartStrategy.getDescriptor(),
          com.volcengine.service.vod.model.business.VodAppsManage.getDescriptor(),
          com.volcengine.service.vod.model.business.VodMeasure.getDescriptor(),
        });
    internal_static_Volcengine_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Volcengine_Vod_Models_Response_VodGetAllPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Volcengine_Vod_Models_Response_VodGetOriginalPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Volcengine_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Volcengine_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUploadMediaResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Volcengine_Vod_Models_Response_VodUploadMediaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUploadMediaResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Volcengine_Vod_Models_Response_VodQueryUploadTaskInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUrlUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Volcengine_Vod_Models_Response_VodUrlUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUrlUploadResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Volcengine_Vod_Models_Response_VodApplyUploadInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Volcengine_Vod_Models_Response_VodCommitUploadInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaInfosResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaInfosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetMediaInfosResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Volcengine_Vod_Models_Response_VodGetRecommendedPosterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaStorageClassResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Volcengine_Vod_Models_Response_VodDeleteTranscodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaTosFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaTosFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDeleteMediaTosFileResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaListResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Volcengine_Vod_Models_Response_VodGetMediaListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetMediaListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Volcengine_Vod_Models_Response_VodGetSubtitleInfoListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Volcengine_Vod_Models_Response_VodGetAuditFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Volcengine_Vod_Models_Response_VodGetMLFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Volcengine_Vod_Models_Response_VodGetBetterFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioInfoForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Volcengine_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Volcengine_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Volcengine_Vod_Models_Response_VodCreateVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Volcengine_Vod_Models_Response_VodDeleteVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Volcengine_Vod_Models_Response_VodListVideoClassificationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListSnapshotsResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Volcengine_Vod_Models_Response_VodListSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListSnapshotsResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetFileListResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Volcengine_Vod_Models_Response_VodGetFileListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetFileListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_Volcengine_Vod_Models_Response_VodExtractMediaMetaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodStartWorkflowResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_Volcengine_Vod_Models_Response_VodStartWorkflowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodStartWorkflowResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_Volcengine_Vod_Models_Response_VodRetrieveTranscodeResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_Volcengine_Vod_Models_Response_VodListWorkflowExecutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_Volcengine_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditProgressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCreateSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_Volcengine_Vod_Models_Response_VodCreateSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCreateSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodListSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_Volcengine_Vod_Models_Response_VodListSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_Volcengine_Vod_Models_Response_VodGetSpaceDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListDomainResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_Volcengine_Vod_Models_Response_VodListDomainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListDomainResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_Volcengine_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListCdnTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_Volcengine_Vod_Models_Response_VodListCdnAccessLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_Volcengine_Vod_Models_Response_VodListCdnTopAccessUrlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_Volcengine_Vod_Models_Response_VodCdnStatisticsCommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_Volcengine_Vod_Models_Response_VodDescribeIPInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_Volcengine_Vod_Models_Response_VodGetContentBlockTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodCreateDomainV2Response_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_Volcengine_Vod_Models_Response_VodCreateDomainV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodCreateDomainV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainExpireV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_Volcengine_Vod_Models_Response_VodAddCallbackSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodSetCallbackEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_Volcengine_Vod_Models_Response_VodSetCallbackEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodSetCallbackEventResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Volcengine_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_Volcengine_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodGetAppInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_Volcengine_Vod_Models_Response_VodGetAppInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodGetAppInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSnapshotDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_Volcengine_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_Volcengine_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Volcengine_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_Volcengine_Vod_Models_Response_VodQueryMediaBlockStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    com.volcengine.service.base.model.base.Base.getDescriptor();
    com.volcengine.service.vod.model.business.VodPlay.getDescriptor();
    com.volcengine.service.vod.model.business.VodMedia.getDescriptor();
    com.volcengine.service.vod.model.business.VodUpload.getDescriptor();
    com.volcengine.service.vod.model.business.VodWorkflow.getDescriptor();
    com.volcengine.service.vod.model.business.VodEdit.getDescriptor();
    com.volcengine.service.vod.model.business.VodSpace.getDescriptor();
    com.volcengine.service.vod.model.business.VodCdn.getDescriptor();
    com.volcengine.service.vod.model.business.VodCommon.getDescriptor();
    com.volcengine.service.vod.model.business.VodSmartStrategy.getDescriptor();
    com.volcengine.service.vod.model.business.VodAppsManage.getDescriptor();
    com.volcengine.service.vod.model.business.VodMeasure.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
