// Code generated by protoc-gen-volcengine-sdk
// source: updateMediaInfo
// DO NOT EDIT!

package com.volcengine.example.vod.media;

import com.volcengine.service.vod.IVodService;
import com.volcengine.service.vod.impl.VodServiceImpl;
public class VodUpdateMediaInfoDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.volcengine.service.vod.model.request.VodUpdateMediaInfoRequest.Builder reqBuilder = com.volcengine.service.vod.model.request.VodUpdateMediaInfoRequest.newBuilder();
			reqBuilder.setVid("your Vid");
			com.google.protobuf.StringValue.Builder posterUriBuilder = com.google.protobuf.StringValue.newBuilder();
			reqBuilder.setPosterUri(posterUriBuilder);
			com.google.protobuf.StringValue.Builder titleBuilder = com.google.protobuf.StringValue.newBuilder();
			reqBuilder.setTitle(titleBuilder);
			com.google.protobuf.StringValue.Builder descriptionBuilder = com.google.protobuf.StringValue.newBuilder();
			reqBuilder.setDescription(descriptionBuilder);
			com.google.protobuf.StringValue.Builder tagsBuilder = com.google.protobuf.StringValue.newBuilder();
			reqBuilder.setTags(tagsBuilder);
			com.google.protobuf.Int64Value.Builder classificationIdBuilder = com.google.protobuf.Int64Value.newBuilder();
			reqBuilder.setClassificationId(classificationIdBuilder);
			
            com.volcengine.service.vod.model.response.VodUpdateMediaInfoResponse resp = vodService.updateMediaInfo(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}