// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/business/stream_manage.proto

package com.volcengine.service.live.model.business;

public interface LiveStreamInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Volcengine.Live.Models.Business.LiveStreamInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 流信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.StreamInfoList StreamInfoList = 1;</code>
   */
  java.util.List<StreamInfoList>
      getStreamInfoListList();
  /**
   * <pre>
   * 流信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.StreamInfoList StreamInfoList = 1;</code>
   */
  StreamInfoList getStreamInfoList(int index);
  /**
   * <pre>
   * 流信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.StreamInfoList StreamInfoList = 1;</code>
   */
  int getStreamInfoListCount();
  /**
   * <pre>
   * 流信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.StreamInfoList StreamInfoList = 1;</code>
   */
  java.util.List<? extends StreamInfoListOrBuilder>
      getStreamInfoListOrBuilderList();
  /**
   * <pre>
   * 流信息列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.StreamInfoList StreamInfoList = 1;</code>
   */
  StreamInfoListOrBuilder getStreamInfoListOrBuilder(
      int index);

  /**
   * <pre>
   * 流数量
   * </pre>
   *
   * <code>int64 RoughCount = 2;</code>
   * @return The roughCount.
   */
  long getRoughCount();
}
