// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/business/relay_source.proto

package com.volcengine.service.live.model.business;

/**
 * Protobuf type {@code Volcengine.Live.Models.Business.RelaySourceConfigList}
 */
public final class RelaySourceConfigList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Volcengine.Live.Models.Business.RelaySourceConfigList)
    RelaySourceConfigListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RelaySourceConfigList.newBuilder() to construct.
  private RelaySourceConfigList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RelaySourceConfigList() {
    relaySourceConfigList_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RelaySourceConfigList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RelaySourceConfigList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              relaySourceConfigList_ = new java.util.ArrayList<RelaySourceConfig>();
              mutable_bitField0_ |= 0x00000001;
            }
            relaySourceConfigList_.add(
                input.readMessage(RelaySourceConfig.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        relaySourceConfigList_ = java.util.Collections.unmodifiableList(relaySourceConfigList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RelaySource.internal_static_Volcengine_Live_Models_Business_RelaySourceConfigList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RelaySource.internal_static_Volcengine_Live_Models_Business_RelaySourceConfigList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RelaySourceConfigList.class, Builder.class);
  }

  public static final int RELAYSOURCECONFIGLIST_FIELD_NUMBER = 1;
  private java.util.List<RelaySourceConfig> relaySourceConfigList_;
  /**
   * <pre>
   * 配置列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
   */
  @Override
  public java.util.List<RelaySourceConfig> getRelaySourceConfigListList() {
    return relaySourceConfigList_;
  }
  /**
   * <pre>
   * 配置列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
   */
  @Override
  public java.util.List<? extends RelaySourceConfigOrBuilder>
      getRelaySourceConfigListOrBuilderList() {
    return relaySourceConfigList_;
  }
  /**
   * <pre>
   * 配置列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
   */
  @Override
  public int getRelaySourceConfigListCount() {
    return relaySourceConfigList_.size();
  }
  /**
   * <pre>
   * 配置列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
   */
  @Override
  public RelaySourceConfig getRelaySourceConfigList(int index) {
    return relaySourceConfigList_.get(index);
  }
  /**
   * <pre>
   * 配置列表
   * </pre>
   *
   * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
   */
  @Override
  public RelaySourceConfigOrBuilder getRelaySourceConfigListOrBuilder(
      int index) {
    return relaySourceConfigList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < relaySourceConfigList_.size(); i++) {
      output.writeMessage(1, relaySourceConfigList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < relaySourceConfigList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, relaySourceConfigList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RelaySourceConfigList)) {
      return super.equals(obj);
    }
    RelaySourceConfigList other = (RelaySourceConfigList) obj;

    if (!getRelaySourceConfigListList()
        .equals(other.getRelaySourceConfigListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRelaySourceConfigListCount() > 0) {
      hash = (37 * hash) + RELAYSOURCECONFIGLIST_FIELD_NUMBER;
      hash = (53 * hash) + getRelaySourceConfigListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RelaySourceConfigList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelaySourceConfigList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelaySourceConfigList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelaySourceConfigList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelaySourceConfigList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelaySourceConfigList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelaySourceConfigList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RelaySourceConfigList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RelaySourceConfigList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RelaySourceConfigList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RelaySourceConfigList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RelaySourceConfigList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RelaySourceConfigList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Volcengine.Live.Models.Business.RelaySourceConfigList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Volcengine.Live.Models.Business.RelaySourceConfigList)
      RelaySourceConfigListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RelaySource.internal_static_Volcengine_Live_Models_Business_RelaySourceConfigList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RelaySource.internal_static_Volcengine_Live_Models_Business_RelaySourceConfigList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RelaySourceConfigList.class, Builder.class);
    }

    // Construct using com.volcengine.service.live.model.business.RelaySourceConfigList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRelaySourceConfigListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (relaySourceConfigListBuilder_ == null) {
        relaySourceConfigList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        relaySourceConfigListBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RelaySource.internal_static_Volcengine_Live_Models_Business_RelaySourceConfigList_descriptor;
    }

    @Override
    public RelaySourceConfigList getDefaultInstanceForType() {
      return RelaySourceConfigList.getDefaultInstance();
    }

    @Override
    public RelaySourceConfigList build() {
      RelaySourceConfigList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RelaySourceConfigList buildPartial() {
      RelaySourceConfigList result = new RelaySourceConfigList(this);
      int from_bitField0_ = bitField0_;
      if (relaySourceConfigListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          relaySourceConfigList_ = java.util.Collections.unmodifiableList(relaySourceConfigList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.relaySourceConfigList_ = relaySourceConfigList_;
      } else {
        result.relaySourceConfigList_ = relaySourceConfigListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RelaySourceConfigList) {
        return mergeFrom((RelaySourceConfigList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RelaySourceConfigList other) {
      if (other == RelaySourceConfigList.getDefaultInstance()) return this;
      if (relaySourceConfigListBuilder_ == null) {
        if (!other.relaySourceConfigList_.isEmpty()) {
          if (relaySourceConfigList_.isEmpty()) {
            relaySourceConfigList_ = other.relaySourceConfigList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRelaySourceConfigListIsMutable();
            relaySourceConfigList_.addAll(other.relaySourceConfigList_);
          }
          onChanged();
        }
      } else {
        if (!other.relaySourceConfigList_.isEmpty()) {
          if (relaySourceConfigListBuilder_.isEmpty()) {
            relaySourceConfigListBuilder_.dispose();
            relaySourceConfigListBuilder_ = null;
            relaySourceConfigList_ = other.relaySourceConfigList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            relaySourceConfigListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRelaySourceConfigListFieldBuilder() : null;
          } else {
            relaySourceConfigListBuilder_.addAllMessages(other.relaySourceConfigList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RelaySourceConfigList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RelaySourceConfigList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<RelaySourceConfig> relaySourceConfigList_ =
      java.util.Collections.emptyList();
    private void ensureRelaySourceConfigListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        relaySourceConfigList_ = new java.util.ArrayList<RelaySourceConfig>(relaySourceConfigList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        RelaySourceConfig, RelaySourceConfig.Builder, RelaySourceConfigOrBuilder> relaySourceConfigListBuilder_;

    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public java.util.List<RelaySourceConfig> getRelaySourceConfigListList() {
      if (relaySourceConfigListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(relaySourceConfigList_);
      } else {
        return relaySourceConfigListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public int getRelaySourceConfigListCount() {
      if (relaySourceConfigListBuilder_ == null) {
        return relaySourceConfigList_.size();
      } else {
        return relaySourceConfigListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public RelaySourceConfig getRelaySourceConfigList(int index) {
      if (relaySourceConfigListBuilder_ == null) {
        return relaySourceConfigList_.get(index);
      } else {
        return relaySourceConfigListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder setRelaySourceConfigList(
        int index, RelaySourceConfig value) {
      if (relaySourceConfigListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.set(index, value);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder setRelaySourceConfigList(
        int index, RelaySourceConfig.Builder builderForValue) {
      if (relaySourceConfigListBuilder_ == null) {
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.set(index, builderForValue.build());
        onChanged();
      } else {
        relaySourceConfigListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder addRelaySourceConfigList(RelaySourceConfig value) {
      if (relaySourceConfigListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.add(value);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder addRelaySourceConfigList(
        int index, RelaySourceConfig value) {
      if (relaySourceConfigListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.add(index, value);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder addRelaySourceConfigList(
        RelaySourceConfig.Builder builderForValue) {
      if (relaySourceConfigListBuilder_ == null) {
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.add(builderForValue.build());
        onChanged();
      } else {
        relaySourceConfigListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder addRelaySourceConfigList(
        int index, RelaySourceConfig.Builder builderForValue) {
      if (relaySourceConfigListBuilder_ == null) {
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.add(index, builderForValue.build());
        onChanged();
      } else {
        relaySourceConfigListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder addAllRelaySourceConfigList(
        Iterable<? extends RelaySourceConfig> values) {
      if (relaySourceConfigListBuilder_ == null) {
        ensureRelaySourceConfigListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, relaySourceConfigList_);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder clearRelaySourceConfigList() {
      if (relaySourceConfigListBuilder_ == null) {
        relaySourceConfigList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public Builder removeRelaySourceConfigList(int index) {
      if (relaySourceConfigListBuilder_ == null) {
        ensureRelaySourceConfigListIsMutable();
        relaySourceConfigList_.remove(index);
        onChanged();
      } else {
        relaySourceConfigListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public RelaySourceConfig.Builder getRelaySourceConfigListBuilder(
        int index) {
      return getRelaySourceConfigListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public RelaySourceConfigOrBuilder getRelaySourceConfigListOrBuilder(
        int index) {
      if (relaySourceConfigListBuilder_ == null) {
        return relaySourceConfigList_.get(index);  } else {
        return relaySourceConfigListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public java.util.List<? extends RelaySourceConfigOrBuilder>
         getRelaySourceConfigListOrBuilderList() {
      if (relaySourceConfigListBuilder_ != null) {
        return relaySourceConfigListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(relaySourceConfigList_);
      }
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public RelaySourceConfig.Builder addRelaySourceConfigListBuilder() {
      return getRelaySourceConfigListFieldBuilder().addBuilder(
          RelaySourceConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public RelaySourceConfig.Builder addRelaySourceConfigListBuilder(
        int index) {
      return getRelaySourceConfigListFieldBuilder().addBuilder(
          index, RelaySourceConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * 配置列表
     * </pre>
     *
     * <code>repeated .Volcengine.Live.Models.Business.RelaySourceConfig RelaySourceConfigList = 1;</code>
     */
    public java.util.List<RelaySourceConfig.Builder>
         getRelaySourceConfigListBuilderList() {
      return getRelaySourceConfigListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        RelaySourceConfig, RelaySourceConfig.Builder, RelaySourceConfigOrBuilder>
        getRelaySourceConfigListFieldBuilder() {
      if (relaySourceConfigListBuilder_ == null) {
        relaySourceConfigListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            RelaySourceConfig, RelaySourceConfig.Builder, RelaySourceConfigOrBuilder>(
                relaySourceConfigList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        relaySourceConfigList_ = null;
      }
      return relaySourceConfigListBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Volcengine.Live.Models.Business.RelaySourceConfigList)
  }

  // @@protoc_insertion_point(class_scope:Volcengine.Live.Models.Business.RelaySourceConfigList)
  private static final RelaySourceConfigList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RelaySourceConfigList();
  }

  public static RelaySourceConfigList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RelaySourceConfigList>
      PARSER = new com.google.protobuf.AbstractParser<RelaySourceConfigList>() {
    @Override
    public RelaySourceConfigList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RelaySourceConfigList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RelaySourceConfigList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RelaySourceConfigList> getParserForType() {
    return PARSER;
  }

  @Override
  public RelaySourceConfigList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

