// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: volcengine/vod/request/request_vod.proto

package com.volcengine.service.vod.model.request;

public final class VodRequest {
  private VodRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAllPlayInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAllPlayInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetPrivateDrmPlayAuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetPrivateDrmPlayAuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetHlsDecryptionKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetHlsDecryptionKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoWithLiveTimeShiftSceneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoWithLiveTimeShiftSceneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUrlUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodQueryUploadTaskInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodQueryUploadTaskInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodApplyUploadInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodApplyUploadInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUploadMediaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUploadMediaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUploadMaterialRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUploadMaterialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCommitUploadInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCommitUploadInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadJsonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUrlUploadJsonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetRecommendedPosterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetRecommendedPosterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaPublishStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaPublishStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaStorageClassRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaStorageClassRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaInfosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetMediaInfosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDeleteTranscodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDeleteTranscodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaTosFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaTosFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetMediaListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetSubtitleInfoListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetSubtitleInfoListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAuditFramesForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAuditFramesForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetMLFramesForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetMLFramesForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetBetterFramesForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetBetterFramesForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioInfoForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAudioInfoForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAutomaticSpeechRecognitionForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAutomaticSpeechRecognitionForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioEventDetectionForAuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAudioEventDetectionForAuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCreateVideoClassificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCreateVideoClassificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateVideoClassificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateVideoClassificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDeleteVideoClassificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDeleteVideoClassificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListVideoClassificationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListVideoClassificationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListSnapshotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListSnapshotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetFileListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetFileListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodExtractMediaMetaTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodExtractMediaMetaTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodStartWorkflowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodStartWorkflowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodRetrieveTranscodeResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodRetrieveTranscodeResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListWorkflowExecutionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListWorkflowExecutionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodSubmitDirectEditTaskAsyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodSubmitDirectEditTaskAsyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditProgressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditProgressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCreateSpaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCreateSpaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetSpaceDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetSpaceDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListSpaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListSpaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceUploadConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceUploadConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodSpaceStorageDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDescribeVodSpaceStorageDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListDomainRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListDomainRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnRefreshTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCreateCdnRefreshTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnPreloadTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCreateCdnPreloadTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnAccessLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnAccessLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTopAccessUrlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnTopAccessUrlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainBandwidthDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainBandwidthDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnUsageDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnUsageDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnStatusDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnStatusDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDescribeIPInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDescribeIPInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnPvDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnPvDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodListCdnHitrateDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodListCdnHitrateDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainTrafficDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainTrafficDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetContentBlockTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetContentBlockTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodCreateDomainV2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodCreateDomainV2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainExpireV2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainExpireV2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainAuthConfigV2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainAuthConfigV2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodAddCallbackSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodAddCallbackSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodSetCallbackEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodSetCallbackEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetSmartStrategyLitePlayInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetSmartStrategyLitePlayInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodGetAppInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodGetAppInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceTranscodeDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceTranscodeDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceAIStatisDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceAIStatisDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceSubtitleStatisDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceSubtitleStatisDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceDetectStatisDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceDetectStatisDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSnapshotDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSnapshotDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceWorkflowDetailDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceWorkflowDetailDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceEditDetailDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceEditDetailDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_DescribeVodPlayFileLogByDomainRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_DescribeVodPlayFileLogByDomainRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockMediaTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockMediaTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodSubmitUnblockMediaTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodSubmitUnblockMediaTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Volcengine_Vod_Models_Request_VodQueryMediaBlockStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Volcengine_Vod_Models_Request_VodQueryMediaBlockStatusRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(volcengine/vod/request/request_vod.pro" +
      "to\022\035Volcengine.Vod.Models.Request\032\036googl" +
      "e/protobuf/wrappers.proto\032*volcengine/vo" +
      "d/business/vod_workflow.proto\032(volcengin" +
      "e/vod/business/vod_upload.proto\"\204\003\n\030VodG" +
      "etAllPlayInfoRequest\022\014\n\004Vids\030\001 \001(\t\022\017\n\007Fo" +
      "rmats\030\002 \001(\t\022\016\n\006Codecs\030\003 \001(\t\022\023\n\013Definitio" +
      "ns\030\004 \001(\t\022\021\n\tFileTypes\030\005 \001(\t\022\021\n\tLogoTypes" +
      "\030\006 \001(\t\022\031\n\021NeedEncryptStream\030\007 \001(\t\022\013\n\003Ssl" +
      "\030\010 \001(\t\022\022\n\nNeedThumbs\030\t \001(\t\022\027\n\017NeedBarrag" +
      "eMask\030\n \001(\t\022\017\n\007CdnType\030\013 \001(\t\022\021\n\tUnionInf" +
      "o\030\014 \001(\t\022\021\n\tPlayScene\030\r \001(\t\022\032\n\022DrmExpireT" +
      "imestamp\030\016 \001(\t\022\017\n\007HDRType\030\017 \001(\t\022 \n\030KeyFr" +
      "ameAlignmentVersion\030\020 \001(\t\022\022\n\nUserAction\030" +
      "\021 \001(\t\022\017\n\007Quality\030\022 \001(\t\"\324\002\n\025VodGetPlayInf" +
      "oRequest\022\013\n\003Vid\030\001 \001(\t\022\016\n\006Format\030\002 \001(\t\022\r\n" +
      "\005Codec\030\003 \001(\t\022\022\n\nDefinition\030\004 \001(\t\022\020\n\010File" +
      "Type\030\005 \001(\t\022\020\n\010LogoType\030\006 \001(\t\022\016\n\006Base64\030\007" +
      " \001(\t\022\013\n\003Ssl\030\010 \001(\t\022\022\n\nNeedThumbs\030\t \001(\t\022\027\n" +
      "\017NeedBarrageMask\030\n \001(\t\022\017\n\007CdnType\030\013 \001(\t\022" +
      "\021\n\tUnionInfo\030\014 \001(\t\022\025\n\rHDRDefinition\030\r \001(" +
      "\t\022\021\n\tPlayScene\030\016 \001(\t\022\032\n\022DrmExpireTimesta" +
      "mp\030\017 \001(\t\022\017\n\007Quality\030\020 \001(\t\022\022\n\nPlayConfig\030" +
      "\021 \001(\t\"g\n\037VodGetPrivateDrmPlayAuthRequest" +
      "\022\017\n\007DrmType\030\001 \001(\t\022\013\n\003Vid\030\002 \001(\t\022\023\n\013PlayAu" +
      "thIds\030\003 \001(\t\022\021\n\tUnionInfo\030\004 \001(\t\"Q\n\035VodGet" +
      "HlsDecryptionKeyRequest\022\024\n\014DrmAuthToken\030" +
      "\001 \001(\t\022\n\n\002Ak\030\002 \001(\t\022\016\n\006Source\030\003 \001(\t\"\230\001\n+Vo" +
      "dGetPlayInfoWithLiveTimeShiftSceneReques" +
      "t\022\021\n\tStoreUris\030\001 \001(\t\022\021\n\tSpaceName\030\002 \001(\t\022" +
      "\013\n\003Ssl\030\003 \001(\t\022\027\n\017ExpireTimestamp\030\004 \001(\t\022\035\n" +
      "\025NeedComposeBucketName\030\005 \001(\t\"m\n\023VodUrlUp" +
      "loadRequest\022\021\n\tSpaceName\030\001 \001(\t\022C\n\007URLSet" +
      "s\030\002 \003(\01322.Volcengine.Vod.Models.Business" +
      ".VodUrlUploadURLSet\"/\n\035VodQueryUploadTas" +
      "kInfoRequest\022\016\n\006JobIds\030\001 \001(\t\"\245\001\n\031VodAppl" +
      "yUploadInfoRequest\022\021\n\tSpaceName\030\001 \001(\t\022\022\n" +
      "\nSessionKey\030\002 \001(\t\022\020\n\010FileSize\030\003 \001(\001\022\020\n\010F" +
      "ileType\030\004 \001(\t\022\020\n\010FileName\030\005 \001(\t\022\024\n\014Stora" +
      "geClass\030\006 \001(\005\022\025\n\rFileExtension\030\007 \001(\t\"\352\001\n" +
      "\025VodUploadMediaRequest\022\021\n\tSpaceName\030\001 \001(" +
      "\t\022\020\n\010FilePath\030\002 \001(\t\022\024\n\014CallbackArgs\030\003 \001(" +
      "\t\022\021\n\tFunctions\030\004 \001(\t\022\020\n\010FileName\030\005 \001(\t\022\024" +
      "\n\014StorageClass\030\006 \001(\005\022\025\n\rFileExtension\030\007 " +
      "\001(\t\022\027\n\017VodUploadSource\030\010 \001(\t\022\026\n\016UploadSt" +
      "rategy\030\t \001(\005\022\023\n\013ParallelNum\030\n \001(\005\"\320\001\n\030Vo" +
      "dUploadMaterialRequest\022\021\n\tSpaceName\030\001 \001(" +
      "\t\022\020\n\010FilePath\030\002 \001(\t\022\024\n\014CallbackArgs\030\003 \001(" +
      "\t\022\021\n\tFunctions\030\004 \001(\t\022\020\n\010FileType\030\005 \001(\t\022\020" +
      "\n\010FileName\030\006 \001(\t\022\025\n\rFileExtension\030\007 \001(\t\022" +
      "\026\n\016UploadStrategy\030\010 \001(\005\022\023\n\013ParallelNum\030\t" +
      " \001(\005\"\205\001\n\032VodCommitUploadInfoRequest\022\021\n\tS" +
      "paceName\030\001 \001(\t\022\022\n\nSessionKey\030\002 \001(\t\022\024\n\014Ca" +
      "llbackArgs\030\003 \001(\t\022\021\n\tFunctions\030\004 \001(\t\022\027\n\017V" +
      "odUploadSource\030\005 \001(\t\"=\n\027VodUrlUploadJson" +
      "Request\022\021\n\tSpaceName\030\001 \001(\t\022\017\n\007URLSets\030\002 " +
      "\001(\t\".\n\036VodGetRecommendedPosterRequest\022\014\n" +
      "\004Vids\030\001 \001(\t\"A\n\"VodUpdateMediaPublishStat" +
      "usRequest\022\013\n\003Vid\030\001 \001(\t\022\016\n\006Status\030\002 \001(\t\"n" +
      "\n!VodUpdateMediaStorageClassRequest\022\014\n\004V" +
      "ids\030\001 \001(\t\022\024\n\014StorageClass\030\002 \001(\t\022\024\n\014Callb" +
      "ackArgs\030\003 \001(\t\022\017\n\007FileIds\030\004 \001(\t\"\234\002\n\031VodUp" +
      "dateMediaInfoRequest\022\013\n\003Vid\030\001 \001(\t\022/\n\tPos" +
      "terUri\030\002 \001(\0132\034.google.protobuf.StringVal" +
      "ue\022+\n\005Title\030\003 \001(\0132\034.google.protobuf.Stri" +
      "ngValue\0221\n\013Description\030\004 \001(\0132\034.google.pr" +
      "otobuf.StringValue\022*\n\004Tags\030\005 \001(\0132\034.googl" +
      "e.protobuf.StringValue\0225\n\020Classification" +
      "Id\030\006 \001(\0132\033.google.protobuf.Int64Value\"\'\n" +
      "\027VodGetMediaInfosRequest\022\014\n\004Vids\030\001 \001(\t\";" +
      "\n\025VodDeleteMediaRequest\022\014\n\004Vids\030\001 \001(\t\022\024\n" +
      "\014CallbackArgs\030\002 \001(\t\"P\n\032VodDeleteTranscod" +
      "esRequest\022\013\n\003Vid\030\001 \001(\t\022\017\n\007FileIds\030\002 \001(\t\022" +
      "\024\n\014CallbackArgs\030\003 \001(\t\"D\n\034VodDeleteMediaT" +
      "osFileRequest\022\021\n\tFileNames\030\001 \003(\t\022\021\n\tSpac" +
      "eName\030\002 \001(\t\"\373\001\n\026VodGetMediaListRequest\022\021" +
      "\n\tSpaceName\030\001 \001(\t\022\013\n\003Vid\030\002 \001(\t\022\016\n\006Status" +
      "\030\003 \001(\t\022\r\n\005Order\030\004 \001(\t\022\014\n\004Tags\030\005 \001(\t\022\021\n\tS" +
      "tartTime\030\006 \001(\t\022\017\n\007EndTime\030\007 \001(\t\022\016\n\006Offse" +
      "t\030\010 \001(\t\022\020\n\010PageSize\030\t \001(\t\022\031\n\021Classificat" +
      "ionIds\030\n \001(\t\022\031\n\021TosStorageClasses\030\013 \001(\t\022" +
      "\030\n\020VodUploadSources\030\014 \001(\t\"\346\001\n\035VodGetSubt" +
      "itleInfoListRequest\022\013\n\003Vid\030\001 \001(\t\022\017\n\007File" +
      "Ids\030\002 \001(\t\022\021\n\tLanguages\030\003 \001(\t\022\017\n\007Formats\030" +
      "\004 \001(\t\022\023\n\013LanguageIds\030\005 \001(\t\022\023\n\013SubtitleId" +
      "s\030\006 \001(\t\022\016\n\006Status\030\007 \001(\t\022\r\n\005Title\030\010 \001(\t\022\013" +
      "\n\003Tag\030\t \001(\t\022\016\n\006Offset\030\n \001(\t\022\020\n\010PageSize\030" +
      "\013 \001(\t\022\013\n\003Ssl\030\014 \001(\t\"r\n\036VodUpdateSubtitleS" +
      "tatusRequest\022\013\n\003Vid\030\001 \001(\t\022\017\n\007FileIds\030\002 \001" +
      "(\t\022\021\n\tLanguages\030\003 \001(\t\022\017\n\007Formats\030\004 \001(\t\022\016" +
      "\n\006Status\030\005 \001(\t\"\265\001\n\034VodUpdateSubtitleInfo" +
      "Request\022\013\n\003Vid\030\001 \001(\t\022\016\n\006FileId\030\002 \001(\t\022\020\n\010" +
      "Language\030\003 \001(\t\022\016\n\006Format\030\004 \001(\t\022+\n\005Title\030" +
      "\006 \001(\0132\034.google.protobuf.StringValue\022)\n\003T" +
      "ag\030\007 \001(\0132\034.google.protobuf.StringValue\"w" +
      "\n VodGetAuditFramesForAuditRequest\022\013\n\003Vi" +
      "d\030\001 \001(\t\022\020\n\010Strategy\030\002 \001(\t\022\031\n\021MinNumberOf" +
      "Frames\030\003 \001(\t\022\031\n\021MaxNumberOfFrames\030\004 \001(\t\"" +
      "\241\002\n\035VodGetMLFramesForAuditRequest\022\013\n\003Vid" +
      "\030\001 \001(\t\022\020\n\010Strategy\030\002 \001(\t\022\020\n\010FrameOpt\030\003 \001" +
      "(\t\022\020\n\010FrameFps\030\004 \001(\t\022\026\n\016NumberOfFrames\030\005" +
      " \001(\t\022\024\n\014CutTimeMills\030\006 \001(\t\022\026\n\016NeedFirstF" +
      "rame\030\007 \001(\t\022\025\n\rNeedLastFrame\030\010 \001(\t\022\025\n\rSta" +
      "rtTimeMill\030\t \001(\t\022\023\n\013EndTimeMill\030\n \001(\t\022\031\n" +
      "\021MinNumberOfFrames\030\013 \001(\t\022\031\n\021MaxNumberOfF" +
      "rames\030\014 \001(\t\"U\n!VodGetBetterFramesForAudi" +
      "tRequest\022\013\n\003Vid\030\001 \001(\t\022\020\n\010Strategy\030\002 \001(\t\022" +
      "\021\n\tCoverRate\030\003 \001(\t\"?\n\036VodGetAudioInfoFor" +
      "AuditRequest\022\013\n\003Vid\030\001 \001(\t\022\020\n\010Strategy\030\002 " +
      "\001(\t\"P\n/VodGetAutomaticSpeechRecognitionF" +
      "orAuditRequest\022\013\n\003Vid\030\001 \001(\t\022\020\n\010Strategy\030" +
      "\002 \001(\t\"I\n(VodGetAudioEventDetectionForAud" +
      "itRequest\022\013\n\003Vid\030\001 \001(\t\022\020\n\010Strategy\030\002 \001(\t" +
      "\"q\n#VodCreateVideoClassificationRequest\022" +
      "\021\n\tSpaceName\030\001 \001(\t\022\r\n\005Level\030\002 \001(\005\022\020\n\010Par" +
      "entId\030\003 \001(\003\022\026\n\016Classification\030\004 \001(\t\"j\n#V" +
      "odUpdateVideoClassificationRequest\022\021\n\tSp" +
      "aceName\030\001 \001(\t\022\030\n\020ClassificationId\030\002 \001(\003\022" +
      "\026\n\016Classification\030\003 \001(\t\"R\n#VodDeleteVide" +
      "oClassificationRequest\022\021\n\tSpaceName\030\001 \001(" +
      "\t\022\030\n\020ClassificationId\030\002 \001(\003\"Q\n\"VodListVi" +
      "deoClassificationsRequest\022\021\n\tSpaceName\030\001" +
      " \001(\t\022\030\n\020ClassificationId\030\002 \001(\003\"&\n\027VodLis" +
      "tSnapshotsRequest\022\013\n\003Vid\030\001 \001(\t\"Z\n\025VodGet" +
      "FileListRequest\022\021\n\tSpaceName\030\001 \001(\t\022\016\n\006Pr" +
      "efix\030\002 \001(\t\022\r\n\005Limit\030\003 \001(\t\022\017\n\007Starter\030\004 \001" +
      "(\t\"-\n\036VodExtractMediaMetaTaskRequest\022\013\n\003" +
      "Vid\030\001 \001(\t\"\216\002\n\027VodStartWorkflowRequest\022\013\n" +
      "\003Vid\030\001 \001(\t\022\022\n\nTemplateId\030\002 \001(\t\022=\n\005Input\030" +
      "\003 \001(\0132..Volcengine.Vod.Models.Business.W" +
      "orkflowParams\022\020\n\010Priority\030\004 \001(\005\022\024\n\014Callb" +
      "ackArgs\030\005 \001(\t\022\031\n\021EnableLowPriority\030\006 \001(\010" +
      "\022<\n\tDirectUrl\030\007 \001(\0132).Volcengine.Vod.Mod" +
      "els.Business.DirectUrl\022\022\n\nTaskListId\030\010 \001" +
      "(\t\"D\n!VodRetrieveTranscodeResultRequest\022" +
      "\013\n\003Vid\030\001 \001(\t\022\022\n\nResultType\030\002 \001(\t\"\237\002\n\037Vod" +
      "ListWorkflowExecutionRequest\022\r\n\005RunId\030\001 " +
      "\001(\t\022\013\n\003Vid\030\002 \001(\t\022\021\n\tSpaceName\030\003 \001(\t\022\022\n\nT" +
      "emplateId\030\004 \001(\t\022\022\n\nTaskListId\030\005 \001(\t\022\031\n\021E" +
      "nableLowPriority\030\006 \001(\t\022\021\n\tJobSource\030\007 \001(" +
      "\t\022\016\n\006Status\030\010 \001(\t\022\021\n\tStartTime\030\t \001(\t\022\017\n\007" +
      "EndTime\030\n \001(\t\022\020\n\010PageSize\030\013 \001(\t\022\016\n\006Offse" +
      "t\030\014 \001(\t\022\022\n\nOrderByKey\030\r \001(\t\022\r\n\005Order\030\016 \001" +
      "(\t\"5\n$VodGetWorkflowExecutionDetailReque" +
      "st\022\r\n\005RunId\030\001 \001(\t\",\n\033VodGetWorkflowResul" +
      "tRequest\022\r\n\005RunId\030\001 \001(\t\"N\n$VodGetWorkflo" +
      "wExecutionStatusRequest\022\r\n\005RunId\030\001 \001(\t\022\027" +
      "\n\017NeedTasksDetail\030\002 \001(\t\"\234\001\n#VodSubmitDir" +
      "ectEditTaskAsyncRequest\022\020\n\010Uploader\030\001 \001(" +
      "\t\022\023\n\013Application\030\002 \001(\t\022\021\n\tEditParam\030\004 \001(" +
      "\014\022\020\n\010Priority\030\005 \001(\005\022\023\n\013CallbackUri\030\006 \001(\t" +
      "\022\024\n\014CallbackArgs\030\007 \001(\t\"/\n\035VodGetDirectEd" +
      "itResultRequest\022\016\n\006ReqIds\030\001 \003(\t\"0\n\037VodGe" +
      "tDirectEditProgressRequest\022\r\n\005ReqId\030\001 \001(" +
      "\t\"v\n\025VodCreateSpaceRequest\022\021\n\tSpaceName\030" +
      "\001 \001(\t\022\023\n\013ProjectName\030\002 \001(\t\022\023\n\013Descriptio" +
      "n\030\003 \001(\t\022\016\n\006Region\030\004 \001(\t\022\020\n\010UserName\030\005 \001(" +
      "\t\"-\n\030VodGetSpaceDetailRequest\022\021\n\tSpaceNa" +
      "me\030\001 \001(\t\"4\n\023VodListSpaceRequest\022\016\n\006Offse" +
      "t\030\001 \001(\001\022\r\n\005Limit\030\002 \001(\001\"u\n\025VodUpdateSpace" +
      "Request\022\021\n\tSpaceName\030\001 \001(\t\022\031\n\021SourceProj" +
      "ectName\030\002 \001(\t\022\031\n\021TargetProjectName\030\003 \001(\t" +
      "\022\023\n\013Description\030\004 \001(\t\"^\n!VodUpdateSpaceU" +
      "ploadConfigRequest\022\021\n\tSpaceName\030\001 \001(\t\022\021\n" +
      "\tConfigKey\030\002 \001(\t\022\023\n\013ConfigValue\030\003 \001(\t\"\201\001" +
      "\n%VodDescribeVodSpaceStorageDataRequest\022" +
      "\021\n\tSpaceList\030\001 \001(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n" +
      "\007EndTime\030\003 \001(\t\022\023\n\013Aggregation\030\004 \001(\005\022\014\n\004T" +
      "ype\030\005 \001(\t\"h\n\024VodListDomainRequest\022\021\n\tSpa" +
      "ceName\030\001 \001(\t\022\022\n\nDomainType\030\002 \001(\t\022\031\n\021Sour" +
      "ceStationType\030\003 \001(\005\022\016\n\006Offset\030\004 \001(\003\"O\n\036V" +
      "odCreateCdnRefreshTaskRequest\022\021\n\tSpaceNa" +
      "me\030\001 \001(\t\022\014\n\004Urls\030\002 \001(\t\022\014\n\004Type\030\003 \001(\t\"A\n\036" +
      "VodCreateCdnPreloadTaskRequest\022\021\n\tSpaceN" +
      "ame\030\001 \001(\t\022\014\n\004Urls\030\002 \001(\t\"\302\001\n\026VodListCdnTa" +
      "sksRequest\022\021\n\tSpaceName\030\001 \001(\t\022\016\n\006TaskId\030" +
      "\002 \001(\t\022\022\n\nDomainName\030\003 \001(\t\022\020\n\010TaskType\030\004 " +
      "\001(\t\022\016\n\006Status\030\005 \001(\t\022\026\n\016StartTimestamp\030\006 " +
      "\001(\005\022\024\n\014EndTimestamp\030\007 \001(\005\022\017\n\007PageNum\030\010 \001" +
      "(\005\022\020\n\010PageSize\030\t \001(\005\"n\n\032VodListCdnAccess" +
      "LogRequest\022\017\n\007Domains\030\001 \001(\t\022\026\n\016StartTime" +
      "stamp\030\002 \001(\005\022\024\n\014EndTimestamp\030\003 \001(\005\022\021\n\tSpa" +
      "ceName\030\004 \001(\t\"p\n\035VodListCdnTopAccessUrlRe" +
      "quest\022\017\n\007Domains\030\001 \001(\t\022\026\n\016StartTimestamp" +
      "\030\002 \001(\005\022\024\n\014EndTimestamp\030\003 \001(\005\022\020\n\010SortType" +
      "\030\004 \001(\t\"\234\001\n(VodDescribeVodDomainBandwidth" +
      "DataRequest\022\022\n\nDomainList\030\001 \001(\t\022\021\n\tStart" +
      "Time\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\023\n\013Aggregati" +
      "on\030\004 \001(\005\022\025\n\rBandwidthType\030\005 \001(\t\022\014\n\004Area\030" +
      "\006 \001(\t\"\212\002\n\032VodListCdnUsageDataRequest\022\017\n\007" +
      "Domains\030\001 \001(\t\022\020\n\010Interval\030\002 \001(\t\022\026\n\016Start" +
      "Timestamp\030\003 \001(\003\022\024\n\014EndTimestamp\030\004 \001(\003\022\020\n" +
      "\010DataType\030\005 \001(\t\022\016\n\006Metric\030\006 \001(\t\022\022\n\nNeedD" +
      "etail\030\007 \001(\010\022\014\n\004Area\030\010 \001(\t\022\016\n\006Region\030\t \001(" +
      "\t\022\013\n\003Isp\030\n \001(\t\022\020\n\010Protocol\030\013 \001(\t\022\021\n\tIpVe" +
      "rsion\030\014 \001(\t\022\025\n\rBillingRegion\030\r \001(\t\"\244\001\n\033V" +
      "odListCdnStatusDataRequest\022\017\n\007Domains\030\001 " +
      "\001(\t\022\020\n\010Interval\030\002 \001(\t\022\026\n\016StartTimestamp\030" +
      "\003 \001(\003\022\024\n\014EndTimestamp\030\004 \001(\003\022\020\n\010DataType\030" +
      "\005 \001(\t\022\016\n\006Metric\030\006 \001(\t\022\022\n\nNeedDetail\030\007 \001(" +
      "\010\"\'\n\030VodDescribeIPInfoRequest\022\013\n\003Ips\030\001 \001" +
      "(\t\"\220\001\n\027VodListCdnPvDataRequest\022\017\n\007Domain" +
      "s\030\001 \001(\t\022\020\n\010Interval\030\002 \001(\t\022\026\n\016StartTimest" +
      "amp\030\003 \001(\003\022\024\n\014EndTimestamp\030\004 \001(\003\022\020\n\010DataT" +
      "ype\030\005 \001(\t\022\022\n\nNeedDetail\030\006 \001(\010\"\223\001\n\034VodLis" +
      "tCdnHitrateDataRequest\022\017\n\007Domains\030\001 \001(\t\022" +
      "\020\n\010Interval\030\002 \001(\t\022\026\n\016StartTimestamp\030\003 \001(" +
      "\003\022\024\n\014EndTimestamp\030\004 \001(\003\022\016\n\006Metric\030\005 \001(\t\022" +
      "\022\n\nNeedDetail\030\006 \001(\010\"\212\001\n&VodDescribeVodDo" +
      "mainTrafficDataRequest\022\022\n\nDomainList\030\001 \001" +
      "(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\023" +
      "\n\013Aggregation\030\004 \001(\005\022\023\n\013TrafficType\030\005 \001(\t" +
      "\"A\n\032VodSubmitBlockTasksRequest\022\020\n\010FileUr" +
      "ls\030\001 \001(\t\022\021\n\tOperation\030\002 \001(\t\"\266\001\n\036VodGetCo" +
      "ntentBlockTasksRequest\022\013\n\003Url\030\001 \001(\t\022\016\n\006D" +
      "omain\030\002 \001(\t\022\016\n\006TaskID\030\003 \001(\t\022\020\n\010TaskType\030" +
      "\004 \001(\t\022\016\n\006Status\030\005 \001(\t\022\021\n\tStartTime\030\006 \001(\003" +
      "\022\017\n\007EndTime\030\007 \001(\003\022\017\n\007PageNum\030\010 \001(\003\022\020\n\010Pa" +
      "geSize\030\t \001(\003\"\301\001\n\030VodCreateDomainV2Reques" +
      "t\022\021\n\tSpaceName\030\001 \001(\t\022\022\n\nDomainType\030\002 \001(\t" +
      "\022\016\n\006Domain\030\003 \001(\t\022\031\n\021SourceStationType\030\005 " +
      "\001(\005\022 \n\030SourceStationAddressType\030\006 \001(\005\022\017\n" +
      "\007Origins\030\007 \001(\t\022\014\n\004Area\030\010 \001(\t\022\022\n\nBucketNa" +
      "me\030\t \001(\t\"g\n\036VodUpdateDomainExpireV2Reque" +
      "st\022\021\n\tSpaceName\030\001 \001(\t\022\022\n\nDomainType\030\002 \001(" +
      "\t\022\016\n\006Domain\030\003 \001(\t\022\016\n\006Expire\030\004 \001(\005\"\217\001\n\"Vo" +
      "dUpdateDomainAuthConfigV2Request\022\021\n\tSpac" +
      "eName\030\001 \001(\t\022\022\n\nDomainType\030\002 \001(\t\022\016\n\006Domai" +
      "n\030\003 \001(\t\022\017\n\007MainKey\030\004 \001(\t\022\021\n\tBackupKey\030\005 " +
      "\001(\t\022\016\n\006Status\030\006 \001(\t\"X\n!VodAddCallbackSub" +
      "scriptionRequest\022\021\n\tSpaceName\030\001 \001(\t\022\013\n\003U" +
      "rl\030\002 \001(\t\022\023\n\013ContentType\030\003 \001(\t\"h\n\032VodSetC" +
      "allbackEventRequest\022\021\n\tSpaceName\030\001 \001(\t\022\016" +
      "\n\006Events\030\002 \001(\t\022\023\n\013AuthEnabled\030\003 \001(\t\022\022\n\nP" +
      "rivateKey\030\004 \001(\t\"\364\001\n&VodGetSmartStrategyL" +
      "itePlayInfoRequest\022\017\n\007PlayUrl\030\001 \001(\t\022\016\n\006F" +
      "ormat\030\002 \001(\t\022\r\n\005Codec\030\003 \001(\t\022\022\n\nDefinition" +
      "\030\004 \001(\t\022\020\n\010FileType\030\005 \001(\t\022\020\n\010LogoType\030\006 \001" +
      "(\t\022\013\n\003Ssl\030\007 \001(\t\022\022\n\nNeedThumbs\030\010 \001(\t\022\027\n\017N" +
      "eedBarrageMask\030\t \001(\t\022\021\n\tUnionInfo\030\n \001(\t\022" +
      "\025\n\rHDRDefinition\030\013 \001(\t\"%\n\024VodGetAppInfoR" +
      "equest\022\r\n\005AppId\030\001 \001(\004\"\320\001\n$DescribeVodSpa" +
      "ceTranscodeDataRequest\022\021\n\tSpaceList\030\001 \001(" +
      "\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\025\n" +
      "\rTranscodeType\030\004 \001(\t\022\025\n\rSpecification\030\005 " +
      "\001(\t\022\025\n\rTaskStageList\030\006 \001(\t\022\023\n\013Aggregatio" +
      "n\030\007 \001(\003\022\027\n\017DetailFieldList\030\010 \001(\t\"\266\001\n#Des" +
      "cribeVodSpaceAIStatisDataRequest\022\021\n\tSpac" +
      "eList\030\001 \001(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTim" +
      "e\030\003 \001(\t\022\023\n\013MediaAiType\030\004 \001(\t\022\025\n\rTaskStag" +
      "eList\030\005 \001(\t\022\023\n\013Aggregation\030\006 \001(\003\022\027\n\017Deta" +
      "ilFieldList\030\007 \001(\t\"\275\001\n)DescribeVodSpaceSu" +
      "btitleStatisDataRequest\022\021\n\tSpaceList\030\001 \001" +
      "(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\024" +
      "\n\014SubtitleType\030\004 \001(\t\022\025\n\rTaskStageList\030\005 " +
      "\001(\t\022\023\n\013Aggregation\030\006 \001(\003\022\027\n\017DetailFieldL" +
      "ist\030\007 \001(\t\"\271\001\n\'DescribeVodSpaceDetectStat" +
      "isDataRequest\022\021\n\tSpaceList\030\001 \001(\t\022\021\n\tStar" +
      "tTime\030\002 \001(\t\022\017\n\007EndTime\030\003 \001(\t\022\022\n\nDetectTy" +
      "pe\030\004 \001(\t\022\025\n\rTaskStageList\030\005 \001(\t\022\023\n\013Aggre" +
      "gation\030\006 \001(\003\022\027\n\017DetailFieldList\030\007 \001(\t\"\262\001" +
      "\n\036DescribeVodSnapshotDataRequest\022\021\n\tSpac" +
      "eList\030\001 \001(\t\022\021\n\tStartTime\030\002 \001(\t\022\017\n\007EndTim" +
      "e\030\003 \001(\t\022\024\n\014SnapshotType\030\004 \001(\t\022\025\n\rTaskSta" +
      "geList\030\005 \001(\t\022\023\n\013Aggregation\030\006 \001(\003\022\027\n\017Det" +
      "ailFieldList\030\007 \001(\t\"\221\001\n)DescribeVodSpaceW" +
      "orkflowDetailDataRequest\022\016\n\006Region\030\001 \001(\t" +
      "\022\r\n\005Space\030\002 \001(\t\022\021\n\tStartTime\030\003 \001(\t\022\017\n\007En" +
      "dTime\030\004 \001(\t\022\020\n\010PageSize\030\005 \001(\003\022\017\n\007PageNum" +
      "\030\006 \001(\003\"\215\001\n%DescribeVodSpaceEditDetailDat" +
      "aRequest\022\016\n\006Region\030\001 \001(\t\022\r\n\005Space\030\002 \001(\t\022" +
      "\021\n\tStartTime\030\003 \001(\t\022\017\n\007EndTime\030\004 \001(\t\022\020\n\010P" +
      "ageSize\030\005 \001(\003\022\017\n\007PageNum\030\006 \001(\003\"_\n%Descri" +
      "beVodPlayFileLogByDomainRequest\022\021\n\tStart" +
      "Time\030\001 \001(\t\022\017\n\007EndTime\030\002 \001(\t\022\022\n\nDomainLis" +
      "t\030\003 \001(\t\"A\n\036VodSubmitBlockMediaTaskReques" +
      "t\022\021\n\tSpaceName\030\001 \001(\t\022\014\n\004Vids\030\002 \001(\t\"C\n Vo" +
      "dSubmitUnblockMediaTaskRequest\022\021\n\tSpaceN" +
      "ame\030\001 \001(\t\022\014\n\004Vids\030\002 \001(\t\"B\n\037VodQueryMedia" +
      "BlockStatusRequest\022\021\n\tSpaceName\030\001 \001(\t\022\014\n" +
      "\004Vids\030\002 \001(\tB\310\001\n(com.volcengine.service.v" +
      "od.model.requestB\nVodRequestP\001Z@github.c" +
      "om/volcengine/volc-sdk-golang/service/vo" +
      "d/models/request\240\001\001\330\001\001\312\002\037Volc\\Service\\Vo" +
      "d\\Models\\Request\342\002#Volc\\Service\\Vod\\Mode" +
      "ls\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.volcengine.service.vod.model.business.VodWorkflow.getDescriptor(),
          com.volcengine.service.vod.model.business.VodUpload.getDescriptor(),
        });
    internal_static_Volcengine_Vod_Models_Request_VodGetAllPlayInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Volcengine_Vod_Models_Request_VodGetAllPlayInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAllPlayInfoRequest_descriptor,
        new java.lang.String[] { "Vids", "Formats", "Codecs", "Definitions", "FileTypes", "LogoTypes", "NeedEncryptStream", "Ssl", "NeedThumbs", "NeedBarrageMask", "CdnType", "UnionInfo", "PlayScene", "DrmExpireTimestamp", "HDRType", "KeyFrameAlignmentVersion", "UserAction", "Quality", });
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoRequest_descriptor,
        new java.lang.String[] { "Vid", "Format", "Codec", "Definition", "FileType", "LogoType", "Base64", "Ssl", "NeedThumbs", "NeedBarrageMask", "CdnType", "UnionInfo", "HDRDefinition", "PlayScene", "DrmExpireTimestamp", "Quality", "PlayConfig", });
    internal_static_Volcengine_Vod_Models_Request_VodGetPrivateDrmPlayAuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Volcengine_Vod_Models_Request_VodGetPrivateDrmPlayAuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetPrivateDrmPlayAuthRequest_descriptor,
        new java.lang.String[] { "DrmType", "Vid", "PlayAuthIds", "UnionInfo", });
    internal_static_Volcengine_Vod_Models_Request_VodGetHlsDecryptionKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Volcengine_Vod_Models_Request_VodGetHlsDecryptionKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetHlsDecryptionKeyRequest_descriptor,
        new java.lang.String[] { "DrmAuthToken", "Ak", "Source", });
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoWithLiveTimeShiftSceneRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoWithLiveTimeShiftSceneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetPlayInfoWithLiveTimeShiftSceneRequest_descriptor,
        new java.lang.String[] { "StoreUris", "SpaceName", "Ssl", "ExpireTimestamp", "NeedComposeBucketName", });
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUrlUploadRequest_descriptor,
        new java.lang.String[] { "SpaceName", "URLSets", });
    internal_static_Volcengine_Vod_Models_Request_VodQueryUploadTaskInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Volcengine_Vod_Models_Request_VodQueryUploadTaskInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodQueryUploadTaskInfoRequest_descriptor,
        new java.lang.String[] { "JobIds", });
    internal_static_Volcengine_Vod_Models_Request_VodApplyUploadInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Volcengine_Vod_Models_Request_VodApplyUploadInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodApplyUploadInfoRequest_descriptor,
        new java.lang.String[] { "SpaceName", "SessionKey", "FileSize", "FileType", "FileName", "StorageClass", "FileExtension", });
    internal_static_Volcengine_Vod_Models_Request_VodUploadMediaRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Volcengine_Vod_Models_Request_VodUploadMediaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUploadMediaRequest_descriptor,
        new java.lang.String[] { "SpaceName", "FilePath", "CallbackArgs", "Functions", "FileName", "StorageClass", "FileExtension", "VodUploadSource", "UploadStrategy", "ParallelNum", });
    internal_static_Volcengine_Vod_Models_Request_VodUploadMaterialRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Volcengine_Vod_Models_Request_VodUploadMaterialRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUploadMaterialRequest_descriptor,
        new java.lang.String[] { "SpaceName", "FilePath", "CallbackArgs", "Functions", "FileType", "FileName", "FileExtension", "UploadStrategy", "ParallelNum", });
    internal_static_Volcengine_Vod_Models_Request_VodCommitUploadInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Volcengine_Vod_Models_Request_VodCommitUploadInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCommitUploadInfoRequest_descriptor,
        new java.lang.String[] { "SpaceName", "SessionKey", "CallbackArgs", "Functions", "VodUploadSource", });
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadJsonRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Volcengine_Vod_Models_Request_VodUrlUploadJsonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUrlUploadJsonRequest_descriptor,
        new java.lang.String[] { "SpaceName", "URLSets", });
    internal_static_Volcengine_Vod_Models_Request_VodGetRecommendedPosterRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Volcengine_Vod_Models_Request_VodGetRecommendedPosterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetRecommendedPosterRequest_descriptor,
        new java.lang.String[] { "Vids", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaPublishStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaPublishStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaPublishStatusRequest_descriptor,
        new java.lang.String[] { "Vid", "Status", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaStorageClassRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaStorageClassRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaStorageClassRequest_descriptor,
        new java.lang.String[] { "Vids", "StorageClass", "CallbackArgs", "FileIds", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateMediaInfoRequest_descriptor,
        new java.lang.String[] { "Vid", "PosterUri", "Title", "Description", "Tags", "ClassificationId", });
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaInfosRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaInfosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetMediaInfosRequest_descriptor,
        new java.lang.String[] { "Vids", });
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaRequest_descriptor,
        new java.lang.String[] { "Vids", "CallbackArgs", });
    internal_static_Volcengine_Vod_Models_Request_VodDeleteTranscodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Volcengine_Vod_Models_Request_VodDeleteTranscodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDeleteTranscodesRequest_descriptor,
        new java.lang.String[] { "Vid", "FileIds", "CallbackArgs", });
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaTosFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaTosFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDeleteMediaTosFileRequest_descriptor,
        new java.lang.String[] { "FileNames", "SpaceName", });
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaListRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Volcengine_Vod_Models_Request_VodGetMediaListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetMediaListRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Vid", "Status", "Order", "Tags", "StartTime", "EndTime", "Offset", "PageSize", "ClassificationIds", "TosStorageClasses", "VodUploadSources", });
    internal_static_Volcengine_Vod_Models_Request_VodGetSubtitleInfoListRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Volcengine_Vod_Models_Request_VodGetSubtitleInfoListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetSubtitleInfoListRequest_descriptor,
        new java.lang.String[] { "Vid", "FileIds", "Languages", "Formats", "LanguageIds", "SubtitleIds", "Status", "Title", "Tag", "Offset", "PageSize", "Ssl", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleStatusRequest_descriptor,
        new java.lang.String[] { "Vid", "FileIds", "Languages", "Formats", "Status", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateSubtitleInfoRequest_descriptor,
        new java.lang.String[] { "Vid", "FileId", "Language", "Format", "Title", "Tag", });
    internal_static_Volcengine_Vod_Models_Request_VodGetAuditFramesForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Volcengine_Vod_Models_Request_VodGetAuditFramesForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAuditFramesForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", "MinNumberOfFrames", "MaxNumberOfFrames", });
    internal_static_Volcengine_Vod_Models_Request_VodGetMLFramesForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Volcengine_Vod_Models_Request_VodGetMLFramesForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetMLFramesForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", "FrameOpt", "FrameFps", "NumberOfFrames", "CutTimeMills", "NeedFirstFrame", "NeedLastFrame", "StartTimeMill", "EndTimeMill", "MinNumberOfFrames", "MaxNumberOfFrames", });
    internal_static_Volcengine_Vod_Models_Request_VodGetBetterFramesForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Volcengine_Vod_Models_Request_VodGetBetterFramesForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetBetterFramesForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", "CoverRate", });
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioInfoForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioInfoForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAudioInfoForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", });
    internal_static_Volcengine_Vod_Models_Request_VodGetAutomaticSpeechRecognitionForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Volcengine_Vod_Models_Request_VodGetAutomaticSpeechRecognitionForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAutomaticSpeechRecognitionForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", });
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioEventDetectionForAuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Volcengine_Vod_Models_Request_VodGetAudioEventDetectionForAuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAudioEventDetectionForAuditRequest_descriptor,
        new java.lang.String[] { "Vid", "Strategy", });
    internal_static_Volcengine_Vod_Models_Request_VodCreateVideoClassificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Volcengine_Vod_Models_Request_VodCreateVideoClassificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCreateVideoClassificationRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Level", "ParentId", "Classification", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateVideoClassificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateVideoClassificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateVideoClassificationRequest_descriptor,
        new java.lang.String[] { "SpaceName", "ClassificationId", "Classification", });
    internal_static_Volcengine_Vod_Models_Request_VodDeleteVideoClassificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Volcengine_Vod_Models_Request_VodDeleteVideoClassificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDeleteVideoClassificationRequest_descriptor,
        new java.lang.String[] { "SpaceName", "ClassificationId", });
    internal_static_Volcengine_Vod_Models_Request_VodListVideoClassificationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Volcengine_Vod_Models_Request_VodListVideoClassificationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListVideoClassificationsRequest_descriptor,
        new java.lang.String[] { "SpaceName", "ClassificationId", });
    internal_static_Volcengine_Vod_Models_Request_VodListSnapshotsRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Volcengine_Vod_Models_Request_VodListSnapshotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListSnapshotsRequest_descriptor,
        new java.lang.String[] { "Vid", });
    internal_static_Volcengine_Vod_Models_Request_VodGetFileListRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_Volcengine_Vod_Models_Request_VodGetFileListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetFileListRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Prefix", "Limit", "Starter", });
    internal_static_Volcengine_Vod_Models_Request_VodExtractMediaMetaTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_Volcengine_Vod_Models_Request_VodExtractMediaMetaTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodExtractMediaMetaTaskRequest_descriptor,
        new java.lang.String[] { "Vid", });
    internal_static_Volcengine_Vod_Models_Request_VodStartWorkflowRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_Volcengine_Vod_Models_Request_VodStartWorkflowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodStartWorkflowRequest_descriptor,
        new java.lang.String[] { "Vid", "TemplateId", "Input", "Priority", "CallbackArgs", "EnableLowPriority", "DirectUrl", "TaskListId", });
    internal_static_Volcengine_Vod_Models_Request_VodRetrieveTranscodeResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_Volcengine_Vod_Models_Request_VodRetrieveTranscodeResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodRetrieveTranscodeResultRequest_descriptor,
        new java.lang.String[] { "Vid", "ResultType", });
    internal_static_Volcengine_Vod_Models_Request_VodListWorkflowExecutionRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_Volcengine_Vod_Models_Request_VodListWorkflowExecutionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListWorkflowExecutionRequest_descriptor,
        new java.lang.String[] { "RunId", "Vid", "SpaceName", "TemplateId", "TaskListId", "EnableLowPriority", "JobSource", "Status", "StartTime", "EndTime", "PageSize", "Offset", "OrderByKey", "Order", });
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionDetailRequest_descriptor,
        new java.lang.String[] { "RunId", });
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowResultRequest_descriptor,
        new java.lang.String[] { "RunId", });
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetWorkflowExecutionStatusRequest_descriptor,
        new java.lang.String[] { "RunId", "NeedTasksDetail", });
    internal_static_Volcengine_Vod_Models_Request_VodSubmitDirectEditTaskAsyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_Volcengine_Vod_Models_Request_VodSubmitDirectEditTaskAsyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodSubmitDirectEditTaskAsyncRequest_descriptor,
        new java.lang.String[] { "Uploader", "Application", "EditParam", "Priority", "CallbackUri", "CallbackArgs", });
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditResultRequest_descriptor,
        new java.lang.String[] { "ReqIds", });
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditProgressRequest_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditProgressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetDirectEditProgressRequest_descriptor,
        new java.lang.String[] { "ReqId", });
    internal_static_Volcengine_Vod_Models_Request_VodCreateSpaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_Volcengine_Vod_Models_Request_VodCreateSpaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCreateSpaceRequest_descriptor,
        new java.lang.String[] { "SpaceName", "ProjectName", "Description", "Region", "UserName", });
    internal_static_Volcengine_Vod_Models_Request_VodGetSpaceDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_Volcengine_Vod_Models_Request_VodGetSpaceDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetSpaceDetailRequest_descriptor,
        new java.lang.String[] { "SpaceName", });
    internal_static_Volcengine_Vod_Models_Request_VodListSpaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_Volcengine_Vod_Models_Request_VodListSpaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListSpaceRequest_descriptor,
        new java.lang.String[] { "Offset", "Limit", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceRequest_descriptor,
        new java.lang.String[] { "SpaceName", "SourceProjectName", "TargetProjectName", "Description", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceUploadConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceUploadConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateSpaceUploadConfigRequest_descriptor,
        new java.lang.String[] { "SpaceName", "ConfigKey", "ConfigValue", });
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodSpaceStorageDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodSpaceStorageDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDescribeVodSpaceStorageDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "Aggregation", "Type", });
    internal_static_Volcengine_Vod_Models_Request_VodListDomainRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_Volcengine_Vod_Models_Request_VodListDomainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListDomainRequest_descriptor,
        new java.lang.String[] { "SpaceName", "DomainType", "SourceStationType", "Offset", });
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnRefreshTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnRefreshTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCreateCdnRefreshTaskRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Urls", "Type", });
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnPreloadTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_Volcengine_Vod_Models_Request_VodCreateCdnPreloadTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCreateCdnPreloadTaskRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Urls", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnTasksRequest_descriptor,
        new java.lang.String[] { "SpaceName", "TaskId", "DomainName", "TaskType", "Status", "StartTimestamp", "EndTimestamp", "PageNum", "PageSize", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnAccessLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnAccessLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnAccessLogRequest_descriptor,
        new java.lang.String[] { "Domains", "StartTimestamp", "EndTimestamp", "SpaceName", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTopAccessUrlRequest_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnTopAccessUrlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnTopAccessUrlRequest_descriptor,
        new java.lang.String[] { "Domains", "StartTimestamp", "EndTimestamp", "SortType", });
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainBandwidthDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainBandwidthDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainBandwidthDataRequest_descriptor,
        new java.lang.String[] { "DomainList", "StartTime", "EndTime", "Aggregation", "BandwidthType", "Area", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnUsageDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnUsageDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnUsageDataRequest_descriptor,
        new java.lang.String[] { "Domains", "Interval", "StartTimestamp", "EndTimestamp", "DataType", "Metric", "NeedDetail", "Area", "Region", "Isp", "Protocol", "IpVersion", "BillingRegion", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnStatusDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnStatusDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnStatusDataRequest_descriptor,
        new java.lang.String[] { "Domains", "Interval", "StartTimestamp", "EndTimestamp", "DataType", "Metric", "NeedDetail", });
    internal_static_Volcengine_Vod_Models_Request_VodDescribeIPInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_Volcengine_Vod_Models_Request_VodDescribeIPInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDescribeIPInfoRequest_descriptor,
        new java.lang.String[] { "Ips", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnPvDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnPvDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnPvDataRequest_descriptor,
        new java.lang.String[] { "Domains", "Interval", "StartTimestamp", "EndTimestamp", "DataType", "NeedDetail", });
    internal_static_Volcengine_Vod_Models_Request_VodListCdnHitrateDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_Volcengine_Vod_Models_Request_VodListCdnHitrateDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodListCdnHitrateDataRequest_descriptor,
        new java.lang.String[] { "Domains", "Interval", "StartTimestamp", "EndTimestamp", "Metric", "NeedDetail", });
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainTrafficDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainTrafficDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodDescribeVodDomainTrafficDataRequest_descriptor,
        new java.lang.String[] { "DomainList", "StartTime", "EndTime", "Aggregation", "TrafficType", });
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockTasksRequest_descriptor,
        new java.lang.String[] { "FileUrls", "Operation", });
    internal_static_Volcengine_Vod_Models_Request_VodGetContentBlockTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_Volcengine_Vod_Models_Request_VodGetContentBlockTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetContentBlockTasksRequest_descriptor,
        new java.lang.String[] { "Url", "Domain", "TaskID", "TaskType", "Status", "StartTime", "EndTime", "PageNum", "PageSize", });
    internal_static_Volcengine_Vod_Models_Request_VodCreateDomainV2Request_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_Volcengine_Vod_Models_Request_VodCreateDomainV2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodCreateDomainV2Request_descriptor,
        new java.lang.String[] { "SpaceName", "DomainType", "Domain", "SourceStationType", "SourceStationAddressType", "Origins", "Area", "BucketName", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainExpireV2Request_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainExpireV2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainExpireV2Request_descriptor,
        new java.lang.String[] { "SpaceName", "DomainType", "Domain", "Expire", });
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainAuthConfigV2Request_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainAuthConfigV2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodUpdateDomainAuthConfigV2Request_descriptor,
        new java.lang.String[] { "SpaceName", "DomainType", "Domain", "MainKey", "BackupKey", "Status", });
    internal_static_Volcengine_Vod_Models_Request_VodAddCallbackSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_Volcengine_Vod_Models_Request_VodAddCallbackSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodAddCallbackSubscriptionRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Url", "ContentType", });
    internal_static_Volcengine_Vod_Models_Request_VodSetCallbackEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_Volcengine_Vod_Models_Request_VodSetCallbackEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodSetCallbackEventRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Events", "AuthEnabled", "PrivateKey", });
    internal_static_Volcengine_Vod_Models_Request_VodGetSmartStrategyLitePlayInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_Volcengine_Vod_Models_Request_VodGetSmartStrategyLitePlayInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetSmartStrategyLitePlayInfoRequest_descriptor,
        new java.lang.String[] { "PlayUrl", "Format", "Codec", "Definition", "FileType", "LogoType", "Ssl", "NeedThumbs", "NeedBarrageMask", "UnionInfo", "HDRDefinition", });
    internal_static_Volcengine_Vod_Models_Request_VodGetAppInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_Volcengine_Vod_Models_Request_VodGetAppInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodGetAppInfoRequest_descriptor,
        new java.lang.String[] { "AppId", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceTranscodeDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceTranscodeDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceTranscodeDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "TranscodeType", "Specification", "TaskStageList", "Aggregation", "DetailFieldList", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceAIStatisDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceAIStatisDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceAIStatisDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "MediaAiType", "TaskStageList", "Aggregation", "DetailFieldList", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceSubtitleStatisDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceSubtitleStatisDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceSubtitleStatisDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "SubtitleType", "TaskStageList", "Aggregation", "DetailFieldList", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceDetectStatisDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceDetectStatisDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceDetectStatisDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "DetectType", "TaskStageList", "Aggregation", "DetailFieldList", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSnapshotDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSnapshotDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSnapshotDataRequest_descriptor,
        new java.lang.String[] { "SpaceList", "StartTime", "EndTime", "SnapshotType", "TaskStageList", "Aggregation", "DetailFieldList", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceWorkflowDetailDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceWorkflowDetailDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceWorkflowDetailDataRequest_descriptor,
        new java.lang.String[] { "Region", "Space", "StartTime", "EndTime", "PageSize", "PageNum", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceEditDetailDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceEditDetailDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodSpaceEditDetailDataRequest_descriptor,
        new java.lang.String[] { "Region", "Space", "StartTime", "EndTime", "PageSize", "PageNum", });
    internal_static_Volcengine_Vod_Models_Request_DescribeVodPlayFileLogByDomainRequest_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_Volcengine_Vod_Models_Request_DescribeVodPlayFileLogByDomainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_DescribeVodPlayFileLogByDomainRequest_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "DomainList", });
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockMediaTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockMediaTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodSubmitBlockMediaTaskRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Vids", });
    internal_static_Volcengine_Vod_Models_Request_VodSubmitUnblockMediaTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_Volcengine_Vod_Models_Request_VodSubmitUnblockMediaTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodSubmitUnblockMediaTaskRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Vids", });
    internal_static_Volcengine_Vod_Models_Request_VodQueryMediaBlockStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_Volcengine_Vod_Models_Request_VodQueryMediaBlockStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Volcengine_Vod_Models_Request_VodQueryMediaBlockStatusRequest_descriptor,
        new java.lang.String[] { "SpaceName", "Vids", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.volcengine.service.vod.model.business.VodWorkflow.getDescriptor();
    com.volcengine.service.vod.model.business.VodUpload.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
